// Code generated by protoc-gen-go. DO NOT EDIT.
// source: db.proto

package jccclientdbpb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// HostInfo - host info
type HostInfo struct {
	HostName             string   `protobuf:"bytes,1,opt,name=hostName,proto3" json:"hostName,omitempty"`
	TaskNums             int32    `protobuf:"varint,2,opt,name=taskNums,proto3" json:"taskNums,omitempty"`
	FailNums             int32    `protobuf:"varint,3,opt,name=failNums,proto3" json:"failNums,omitempty"`
	LastTime             int64    `protobuf:"varint,4,opt,name=lastTime,proto3" json:"lastTime,omitempty"`
	LastFailTime         int64    `protobuf:"varint,5,opt,name=lastFailTime,proto3" json:"lastFailTime,omitempty"`
	StartSleepTime       int64    `protobuf:"varint,6,opt,name=startSleepTime,proto3" json:"startSleepTime,omitempty"`
	SleepTime            int64    `protobuf:"varint,7,opt,name=sleepTime,proto3" json:"sleepTime,omitempty"`
	MultiNums            int32    `protobuf:"varint,8,opt,name=multiNums,proto3" json:"multiNums,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HostInfo) Reset()         { *m = HostInfo{} }
func (m *HostInfo) String() string { return proto.CompactTextString(m) }
func (*HostInfo) ProtoMessage()    {}
func (*HostInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_db_65bc0ca74e2e0cd2, []int{0}
}
func (m *HostInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HostInfo.Unmarshal(m, b)
}
func (m *HostInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HostInfo.Marshal(b, m, deterministic)
}
func (dst *HostInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HostInfo.Merge(dst, src)
}
func (m *HostInfo) XXX_Size() int {
	return xxx_messageInfo_HostInfo.Size(m)
}
func (m *HostInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_HostInfo.DiscardUnknown(m)
}

var xxx_messageInfo_HostInfo proto.InternalMessageInfo

func (m *HostInfo) GetHostName() string {
	if m != nil {
		return m.HostName
	}
	return ""
}

func (m *HostInfo) GetTaskNums() int32 {
	if m != nil {
		return m.TaskNums
	}
	return 0
}

func (m *HostInfo) GetFailNums() int32 {
	if m != nil {
		return m.FailNums
	}
	return 0
}

func (m *HostInfo) GetLastTime() int64 {
	if m != nil {
		return m.LastTime
	}
	return 0
}

func (m *HostInfo) GetLastFailTime() int64 {
	if m != nil {
		return m.LastFailTime
	}
	return 0
}

func (m *HostInfo) GetStartSleepTime() int64 {
	if m != nil {
		return m.StartSleepTime
	}
	return 0
}

func (m *HostInfo) GetSleepTime() int64 {
	if m != nil {
		return m.SleepTime
	}
	return 0
}

func (m *HostInfo) GetMultiNums() int32 {
	if m != nil {
		return m.MultiNums
	}
	return 0
}

func init() {
	proto.RegisterType((*HostInfo)(nil), "jccclientdbpb.HostInfo")
}

func init() { proto.RegisterFile("db.proto", fileDescriptor_db_65bc0ca74e2e0cd2) }

var fileDescriptor_db_65bc0ca74e2e0cd2 = []byte{
	// 201 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0xd0, 0x31, 0x6e, 0x83, 0x30,
	0x14, 0x06, 0x60, 0x19, 0x0a, 0x35, 0x56, 0xdb, 0xc1, 0x13, 0xaa, 0x3a, 0x20, 0x86, 0x8a, 0xa9,
	0x4b, 0xef, 0x50, 0x35, 0x0b, 0x03, 0xc9, 0x05, 0x6c, 0x30, 0x8a, 0x13, 0x1b, 0x23, 0xfc, 0xb8,
	0x40, 0x4e, 0x1e, 0xf9, 0x45, 0x31, 0x4a, 0x36, 0xff, 0xff, 0xf7, 0x0f, 0x4f, 0x66, 0x74, 0x90,
	0x3f, 0xf3, 0xe2, 0xc0, 0xf1, 0xf7, 0x53, 0xdf, 0xf7, 0x46, 0xab, 0x09, 0x06, 0x39, 0xcb, 0xfa,
	0x92, 0x30, 0xfa, 0xef, 0x3c, 0xec, 0xa6, 0xd1, 0xf1, 0x4f, 0x46, 0x8f, 0xce, 0x43, 0x2b, 0xac,
	0x2a, 0x49, 0x45, 0x9a, 0xa2, 0x8b, 0x39, 0x18, 0x08, 0x7f, 0x6e, 0x57, 0xeb, 0xcb, 0xa4, 0x22,
	0x4d, 0xd6, 0xc5, 0x1c, 0x6c, 0x14, 0xda, 0xa0, 0xa5, 0x37, 0xbb, 0xe7, 0x60, 0x46, 0x78, 0x38,
	0x68, 0xab, 0xca, 0x97, 0x8a, 0x34, 0x69, 0x17, 0x33, 0xaf, 0xd9, 0x5b, 0x78, 0xff, 0x09, 0x6d,
	0xd0, 0x33, 0xf4, 0x87, 0x8e, 0x7f, 0xb3, 0x0f, 0x0f, 0x62, 0x81, 0xbd, 0x51, 0x6a, 0xc6, 0x55,
	0x8e, 0xab, 0xa7, 0x96, 0x7f, 0xb1, 0xc2, 0xc7, 0xc9, 0x2b, 0x4e, 0xb6, 0x22, 0xa8, 0x5d, 0x0d,
	0x68, 0x3c, 0x91, 0xe2, 0x89, 0x5b, 0x21, 0x73, 0xfc, 0x9a, 0xdf, 0x6b, 0x00, 0x00, 0x00, 0xff,
	0xff, 0x33, 0x38, 0x44, 0x7b, 0x26, 0x01, 0x00, 0x00,
}
