// Code generated by protoc-gen-go. DO NOT EDIT.
// source: db.proto

package jccclientdbpb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// HostInfo - host info
type HostInfo struct {
	HostName       string `protobuf:"bytes,1,opt,name=hostName,proto3" json:"hostName,omitempty"`
	TaskNums       int32  `protobuf:"varint,2,opt,name=taskNums,proto3" json:"taskNums,omitempty"`
	FailNums       int32  `protobuf:"varint,3,opt,name=failNums,proto3" json:"failNums,omitempty"`
	LastTime       int64  `protobuf:"varint,4,opt,name=lastTime,proto3" json:"lastTime,omitempty"`
	LastFailTime   int64  `protobuf:"varint,5,opt,name=lastFailTime,proto3" json:"lastFailTime,omitempty"`
	StartSleepTime int64  `protobuf:"varint,6,opt,name=startSleepTime,proto3" json:"startSleepTime,omitempty"`
	SleepTime      int64  `protobuf:"varint,7,opt,name=sleepTime,proto3" json:"sleepTime,omitempty"`
	MultiNums      int32  `protobuf:"varint,8,opt,name=multiNums,proto3" json:"multiNums,omitempty"`
	// startTime - 这个用来统计这次错误之前，请求次数用的
	StartTime int64 `protobuf:"varint,9,opt,name=startTime,proto3" json:"startTime,omitempty"`
	// curNums - 同上
	CurNums int64 `protobuf:"varint,10,opt,name=curNums,proto3" json:"curNums,omitempty"`
	// sleepTimeAtStart - sleep time at start task
	SleepTimeAtStart int32 `protobuf:"varint,11,opt,name=sleepTimeAtStart,proto3" json:"sleepTimeAtStart,omitempty"` // Deprecated: Do not use.
	// sleepTimeMsAtStart - sleep time (ms) at start task
	SleepTimeMsAtStart   int32    `protobuf:"varint,12,opt,name=sleepTimeMsAtStart,proto3" json:"sleepTimeMsAtStart,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HostInfo) Reset()         { *m = HostInfo{} }
func (m *HostInfo) String() string { return proto.CompactTextString(m) }
func (*HostInfo) ProtoMessage()    {}
func (*HostInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_db_d8efbce692cc52c4, []int{0}
}
func (m *HostInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HostInfo.Unmarshal(m, b)
}
func (m *HostInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HostInfo.Marshal(b, m, deterministic)
}
func (dst *HostInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HostInfo.Merge(dst, src)
}
func (m *HostInfo) XXX_Size() int {
	return xxx_messageInfo_HostInfo.Size(m)
}
func (m *HostInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_HostInfo.DiscardUnknown(m)
}

var xxx_messageInfo_HostInfo proto.InternalMessageInfo

func (m *HostInfo) GetHostName() string {
	if m != nil {
		return m.HostName
	}
	return ""
}

func (m *HostInfo) GetTaskNums() int32 {
	if m != nil {
		return m.TaskNums
	}
	return 0
}

func (m *HostInfo) GetFailNums() int32 {
	if m != nil {
		return m.FailNums
	}
	return 0
}

func (m *HostInfo) GetLastTime() int64 {
	if m != nil {
		return m.LastTime
	}
	return 0
}

func (m *HostInfo) GetLastFailTime() int64 {
	if m != nil {
		return m.LastFailTime
	}
	return 0
}

func (m *HostInfo) GetStartSleepTime() int64 {
	if m != nil {
		return m.StartSleepTime
	}
	return 0
}

func (m *HostInfo) GetSleepTime() int64 {
	if m != nil {
		return m.SleepTime
	}
	return 0
}

func (m *HostInfo) GetMultiNums() int32 {
	if m != nil {
		return m.MultiNums
	}
	return 0
}

func (m *HostInfo) GetStartTime() int64 {
	if m != nil {
		return m.StartTime
	}
	return 0
}

func (m *HostInfo) GetCurNums() int64 {
	if m != nil {
		return m.CurNums
	}
	return 0
}

// Deprecated: Do not use.
func (m *HostInfo) GetSleepTimeAtStart() int32 {
	if m != nil {
		return m.SleepTimeAtStart
	}
	return 0
}

func (m *HostInfo) GetSleepTimeMsAtStart() int32 {
	if m != nil {
		return m.SleepTimeMsAtStart
	}
	return 0
}

func init() {
	proto.RegisterType((*HostInfo)(nil), "jccclientdbpb.HostInfo")
}

func init() { proto.RegisterFile("db.proto", fileDescriptor_db_d8efbce692cc52c4) }

var fileDescriptor_db_d8efbce692cc52c4 = []byte{
	// 253 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x91, 0xc1, 0x4e, 0xc3, 0x30,
	0x10, 0x44, 0xe5, 0x86, 0xb6, 0xc9, 0x52, 0x10, 0xda, 0x93, 0x85, 0x38, 0x44, 0x3d, 0xa0, 0x9c,
	0x72, 0xe1, 0x0b, 0xe0, 0x80, 0xe0, 0x40, 0x0f, 0x29, 0x3f, 0xe0, 0xa4, 0xae, 0x30, 0x38, 0x75,
	0x14, 0x6f, 0x7e, 0x86, 0xaf, 0x45, 0x5e, 0xb0, 0x2b, 0xa0, 0xb7, 0xcc, 0xbc, 0x99, 0xcd, 0x48,
	0x86, 0x7c, 0xd7, 0xd6, 0xc3, 0xe8, 0xc8, 0xe1, 0xc5, 0x7b, 0xd7, 0x75, 0xd6, 0xe8, 0x03, 0xed,
	0xda, 0xa1, 0x5d, 0x7f, 0x66, 0x90, 0x3f, 0x39, 0x4f, 0xcf, 0x87, 0xbd, 0xc3, 0x6b, 0xc8, 0xdf,
	0x9c, 0xa7, 0x8d, 0xea, 0xb5, 0x14, 0xa5, 0xa8, 0x8a, 0x26, 0xe9, 0xc0, 0x48, 0xf9, 0x8f, 0xcd,
	0xd4, 0x7b, 0x39, 0x2b, 0x45, 0x35, 0x6f, 0x92, 0x0e, 0x6c, 0xaf, 0x8c, 0x65, 0x96, 0x7d, 0xb3,
	0xa8, 0x03, 0xb3, 0xca, 0xd3, 0xab, 0xe9, 0xb5, 0x3c, 0x2b, 0x45, 0x95, 0x35, 0x49, 0xe3, 0x1a,
	0x56, 0xe1, 0xfb, 0x51, 0x19, 0xcb, 0x7c, 0xce, 0xfc, 0x97, 0x87, 0xb7, 0x70, 0xe9, 0x49, 0x8d,
	0xb4, 0xb5, 0x5a, 0x0f, 0x9c, 0x5a, 0x70, 0xea, 0x8f, 0x8b, 0x37, 0x50, 0xf8, 0x14, 0x59, 0x72,
	0xe4, 0x68, 0x04, 0xda, 0x4f, 0x96, 0x0c, 0x4f, 0xcc, 0x79, 0xe2, 0xd1, 0xe0, 0x6e, 0xb8, 0xc6,
	0xdd, 0xe2, 0xa7, 0x1b, 0x0d, 0x94, 0xb0, 0xec, 0xa6, 0x91, 0x9b, 0xc0, 0x2c, 0x4a, 0xac, 0xe1,
	0x2a, 0xfd, 0xe2, 0x9e, 0xb6, 0xa1, 0x21, 0xcf, 0xc3, 0xf1, 0x87, 0x99, 0x14, 0xcd, 0x3f, 0x86,
	0x35, 0x60, 0xf2, 0x5e, 0x7c, 0x6c, 0xac, 0x78, 0xce, 0x09, 0xd2, 0x2e, 0xf8, 0xc9, 0xee, 0xbe,
	0x02, 0x00, 0x00, 0xff, 0xff, 0x8d, 0x0f, 0x18, 0x4c, 0xbe, 0x01, 0x00, 0x00,
}
