// Code generated by protoc-gen-go. DO NOT EDIT.
// source: alimama.proto

package jarviscrawlercore

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// AlimamaMode - alimama mode
type AlimamaMode int32

const (
	// ALIMMM_KEEPALIVE - keepalive
	AlimamaMode_ALIMMM_KEEPALIVE AlimamaMode = 0
	// ALIMMM_SEARCH - search
	AlimamaMode_ALIMMM_SEARCH AlimamaMode = 1
	// ALIMMM_GETTOP - get top
	AlimamaMode_ALIMMM_GETTOP AlimamaMode = 2
)

var AlimamaMode_name = map[int32]string{
	0: "ALIMMM_KEEPALIVE",
	1: "ALIMMM_SEARCH",
	2: "ALIMMM_GETTOP",
}
var AlimamaMode_value = map[string]int32{
	"ALIMMM_KEEPALIVE": 0,
	"ALIMMM_SEARCH":    1,
	"ALIMMM_GETTOP":    2,
}

func (x AlimamaMode) String() string {
	return proto.EnumName(AlimamaMode_name, int32(x))
}
func (AlimamaMode) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_alimama_5e1a65255b69148d, []int{0}
}

// AlimamaProduct - alimama product
type AlimamaProduct struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Url                  string   `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	Shop                 string   `protobuf:"bytes,3,opt,name=shop,proto3" json:"shop,omitempty"`
	Img                  string   `protobuf:"bytes,4,opt,name=img,proto3" json:"img,omitempty"`
	LastCoupon           float32  `protobuf:"fixed32,5,opt,name=lastCoupon,proto3" json:"lastCoupon,omitempty"`
	CurPrice             float32  `protobuf:"fixed32,6,opt,name=curPrice,proto3" json:"curPrice,omitempty"`
	Rebate               float32  `protobuf:"fixed32,7,opt,name=rebate,proto3" json:"rebate,omitempty"`
	Commission           float32  `protobuf:"fixed32,8,opt,name=commission,proto3" json:"commission,omitempty"`
	MoneyQuan            float32  `protobuf:"fixed32,9,opt,name=moneyQuan,proto3" json:"moneyQuan,omitempty"`
	ShopType             string   `protobuf:"bytes,10,opt,name=shopType,proto3" json:"shopType,omitempty"`
	SalesVolume          int32    `protobuf:"varint,11,opt,name=salesVolume,proto3" json:"salesVolume,omitempty"`
	Shopurl              string   `protobuf:"bytes,12,opt,name=shopurl,proto3" json:"shopurl,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AlimamaProduct) Reset()         { *m = AlimamaProduct{} }
func (m *AlimamaProduct) String() string { return proto.CompactTextString(m) }
func (*AlimamaProduct) ProtoMessage()    {}
func (*AlimamaProduct) Descriptor() ([]byte, []int) {
	return fileDescriptor_alimama_5e1a65255b69148d, []int{0}
}
func (m *AlimamaProduct) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AlimamaProduct.Unmarshal(m, b)
}
func (m *AlimamaProduct) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AlimamaProduct.Marshal(b, m, deterministic)
}
func (dst *AlimamaProduct) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AlimamaProduct.Merge(dst, src)
}
func (m *AlimamaProduct) XXX_Size() int {
	return xxx_messageInfo_AlimamaProduct.Size(m)
}
func (m *AlimamaProduct) XXX_DiscardUnknown() {
	xxx_messageInfo_AlimamaProduct.DiscardUnknown(m)
}

var xxx_messageInfo_AlimamaProduct proto.InternalMessageInfo

func (m *AlimamaProduct) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *AlimamaProduct) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *AlimamaProduct) GetShop() string {
	if m != nil {
		return m.Shop
	}
	return ""
}

func (m *AlimamaProduct) GetImg() string {
	if m != nil {
		return m.Img
	}
	return ""
}

func (m *AlimamaProduct) GetLastCoupon() float32 {
	if m != nil {
		return m.LastCoupon
	}
	return 0
}

func (m *AlimamaProduct) GetCurPrice() float32 {
	if m != nil {
		return m.CurPrice
	}
	return 0
}

func (m *AlimamaProduct) GetRebate() float32 {
	if m != nil {
		return m.Rebate
	}
	return 0
}

func (m *AlimamaProduct) GetCommission() float32 {
	if m != nil {
		return m.Commission
	}
	return 0
}

func (m *AlimamaProduct) GetMoneyQuan() float32 {
	if m != nil {
		return m.MoneyQuan
	}
	return 0
}

func (m *AlimamaProduct) GetShopType() string {
	if m != nil {
		return m.ShopType
	}
	return ""
}

func (m *AlimamaProduct) GetSalesVolume() int32 {
	if m != nil {
		return m.SalesVolume
	}
	return 0
}

func (m *AlimamaProduct) GetShopurl() string {
	if m != nil {
		return m.Shopurl
	}
	return ""
}

// AlimamaTopProduct - alimama top product
type AlimamaTopProduct struct {
	Category             []string          `protobuf:"bytes,1,rep,name=category,proto3" json:"category,omitempty"`
	Products             []*AlimamaProduct `protobuf:"bytes,2,rep,name=products,proto3" json:"products,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *AlimamaTopProduct) Reset()         { *m = AlimamaTopProduct{} }
func (m *AlimamaTopProduct) String() string { return proto.CompactTextString(m) }
func (*AlimamaTopProduct) ProtoMessage()    {}
func (*AlimamaTopProduct) Descriptor() ([]byte, []int) {
	return fileDescriptor_alimama_5e1a65255b69148d, []int{1}
}
func (m *AlimamaTopProduct) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AlimamaTopProduct.Unmarshal(m, b)
}
func (m *AlimamaTopProduct) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AlimamaTopProduct.Marshal(b, m, deterministic)
}
func (dst *AlimamaTopProduct) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AlimamaTopProduct.Merge(dst, src)
}
func (m *AlimamaTopProduct) XXX_Size() int {
	return xxx_messageInfo_AlimamaTopProduct.Size(m)
}
func (m *AlimamaTopProduct) XXX_DiscardUnknown() {
	xxx_messageInfo_AlimamaTopProduct.DiscardUnknown(m)
}

var xxx_messageInfo_AlimamaTopProduct proto.InternalMessageInfo

func (m *AlimamaTopProduct) GetCategory() []string {
	if m != nil {
		return m.Category
	}
	return nil
}

func (m *AlimamaTopProduct) GetProducts() []*AlimamaProduct {
	if m != nil {
		return m.Products
	}
	return nil
}

// AlimamaTopInfo - alimama top info
type AlimamaTopInfo struct {
	Lst                  []*AlimamaTopProduct `protobuf:"bytes,1,rep,name=lst,proto3" json:"lst,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *AlimamaTopInfo) Reset()         { *m = AlimamaTopInfo{} }
func (m *AlimamaTopInfo) String() string { return proto.CompactTextString(m) }
func (*AlimamaTopInfo) ProtoMessage()    {}
func (*AlimamaTopInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_alimama_5e1a65255b69148d, []int{2}
}
func (m *AlimamaTopInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AlimamaTopInfo.Unmarshal(m, b)
}
func (m *AlimamaTopInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AlimamaTopInfo.Marshal(b, m, deterministic)
}
func (dst *AlimamaTopInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AlimamaTopInfo.Merge(dst, src)
}
func (m *AlimamaTopInfo) XXX_Size() int {
	return xxx_messageInfo_AlimamaTopInfo.Size(m)
}
func (m *AlimamaTopInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_AlimamaTopInfo.DiscardUnknown(m)
}

var xxx_messageInfo_AlimamaTopInfo proto.InternalMessageInfo

func (m *AlimamaTopInfo) GetLst() []*AlimamaTopProduct {
	if m != nil {
		return m.Lst
	}
	return nil
}

// AlimamaProducts - alimama products
type AlimamaProducts struct {
	Text                 string            `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	Products             []*AlimamaProduct `protobuf:"bytes,2,rep,name=products,proto3" json:"products,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *AlimamaProducts) Reset()         { *m = AlimamaProducts{} }
func (m *AlimamaProducts) String() string { return proto.CompactTextString(m) }
func (*AlimamaProducts) ProtoMessage()    {}
func (*AlimamaProducts) Descriptor() ([]byte, []int) {
	return fileDescriptor_alimama_5e1a65255b69148d, []int{3}
}
func (m *AlimamaProducts) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AlimamaProducts.Unmarshal(m, b)
}
func (m *AlimamaProducts) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AlimamaProducts.Marshal(b, m, deterministic)
}
func (dst *AlimamaProducts) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AlimamaProducts.Merge(dst, src)
}
func (m *AlimamaProducts) XXX_Size() int {
	return xxx_messageInfo_AlimamaProducts.Size(m)
}
func (m *AlimamaProducts) XXX_DiscardUnknown() {
	xxx_messageInfo_AlimamaProducts.DiscardUnknown(m)
}

var xxx_messageInfo_AlimamaProducts proto.InternalMessageInfo

func (m *AlimamaProducts) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

func (m *AlimamaProducts) GetProducts() []*AlimamaProduct {
	if m != nil {
		return m.Products
	}
	return nil
}

// RequestAlimama - request alimama
type RequestAlimama struct {
	Mode                 AlimamaMode `protobuf:"varint,1,opt,name=mode,proto3,enum=jarviscrawlercore.AlimamaMode" json:"mode,omitempty"`
	Text                 string      `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *RequestAlimama) Reset()         { *m = RequestAlimama{} }
func (m *RequestAlimama) String() string { return proto.CompactTextString(m) }
func (*RequestAlimama) ProtoMessage()    {}
func (*RequestAlimama) Descriptor() ([]byte, []int) {
	return fileDescriptor_alimama_5e1a65255b69148d, []int{4}
}
func (m *RequestAlimama) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RequestAlimama.Unmarshal(m, b)
}
func (m *RequestAlimama) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RequestAlimama.Marshal(b, m, deterministic)
}
func (dst *RequestAlimama) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RequestAlimama.Merge(dst, src)
}
func (m *RequestAlimama) XXX_Size() int {
	return xxx_messageInfo_RequestAlimama.Size(m)
}
func (m *RequestAlimama) XXX_DiscardUnknown() {
	xxx_messageInfo_RequestAlimama.DiscardUnknown(m)
}

var xxx_messageInfo_RequestAlimama proto.InternalMessageInfo

func (m *RequestAlimama) GetMode() AlimamaMode {
	if m != nil {
		return m.Mode
	}
	return AlimamaMode_ALIMMM_KEEPALIVE
}

func (m *RequestAlimama) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

// ReplyAlimama - reply alimama
type ReplyAlimama struct {
	Mode AlimamaMode `protobuf:"varint,1,opt,name=mode,proto3,enum=jarviscrawlercore.AlimamaMode" json:"mode,omitempty"`
	// Types that are valid to be assigned to Reply:
	//	*ReplyAlimama_Products
	//	*ReplyAlimama_TopInfo
	Reply                isReplyAlimama_Reply `protobuf_oneof:"reply"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *ReplyAlimama) Reset()         { *m = ReplyAlimama{} }
func (m *ReplyAlimama) String() string { return proto.CompactTextString(m) }
func (*ReplyAlimama) ProtoMessage()    {}
func (*ReplyAlimama) Descriptor() ([]byte, []int) {
	return fileDescriptor_alimama_5e1a65255b69148d, []int{5}
}
func (m *ReplyAlimama) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReplyAlimama.Unmarshal(m, b)
}
func (m *ReplyAlimama) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReplyAlimama.Marshal(b, m, deterministic)
}
func (dst *ReplyAlimama) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReplyAlimama.Merge(dst, src)
}
func (m *ReplyAlimama) XXX_Size() int {
	return xxx_messageInfo_ReplyAlimama.Size(m)
}
func (m *ReplyAlimama) XXX_DiscardUnknown() {
	xxx_messageInfo_ReplyAlimama.DiscardUnknown(m)
}

var xxx_messageInfo_ReplyAlimama proto.InternalMessageInfo

type isReplyAlimama_Reply interface {
	isReplyAlimama_Reply()
}

type ReplyAlimama_Products struct {
	Products *AlimamaProducts `protobuf:"bytes,100,opt,name=products,proto3,oneof"`
}
type ReplyAlimama_TopInfo struct {
	TopInfo *AlimamaTopInfo `protobuf:"bytes,101,opt,name=topInfo,proto3,oneof"`
}

func (*ReplyAlimama_Products) isReplyAlimama_Reply() {}
func (*ReplyAlimama_TopInfo) isReplyAlimama_Reply()  {}

func (m *ReplyAlimama) GetReply() isReplyAlimama_Reply {
	if m != nil {
		return m.Reply
	}
	return nil
}

func (m *ReplyAlimama) GetMode() AlimamaMode {
	if m != nil {
		return m.Mode
	}
	return AlimamaMode_ALIMMM_KEEPALIVE
}

func (m *ReplyAlimama) GetProducts() *AlimamaProducts {
	if x, ok := m.GetReply().(*ReplyAlimama_Products); ok {
		return x.Products
	}
	return nil
}

func (m *ReplyAlimama) GetTopInfo() *AlimamaTopInfo {
	if x, ok := m.GetReply().(*ReplyAlimama_TopInfo); ok {
		return x.TopInfo
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*ReplyAlimama) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _ReplyAlimama_OneofMarshaler, _ReplyAlimama_OneofUnmarshaler, _ReplyAlimama_OneofSizer, []interface{}{
		(*ReplyAlimama_Products)(nil),
		(*ReplyAlimama_TopInfo)(nil),
	}
}

func _ReplyAlimama_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*ReplyAlimama)
	// reply
	switch x := m.Reply.(type) {
	case *ReplyAlimama_Products:
		b.EncodeVarint(100<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Products); err != nil {
			return err
		}
	case *ReplyAlimama_TopInfo:
		b.EncodeVarint(101<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.TopInfo); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("ReplyAlimama.Reply has unexpected type %T", x)
	}
	return nil
}

func _ReplyAlimama_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*ReplyAlimama)
	switch tag {
	case 100: // reply.products
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(AlimamaProducts)
		err := b.DecodeMessage(msg)
		m.Reply = &ReplyAlimama_Products{msg}
		return true, err
	case 101: // reply.topInfo
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(AlimamaTopInfo)
		err := b.DecodeMessage(msg)
		m.Reply = &ReplyAlimama_TopInfo{msg}
		return true, err
	default:
		return false, nil
	}
}

func _ReplyAlimama_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*ReplyAlimama)
	// reply
	switch x := m.Reply.(type) {
	case *ReplyAlimama_Products:
		s := proto.Size(x.Products)
		n += 2 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *ReplyAlimama_TopInfo:
		s := proto.Size(x.TopInfo)
		n += 2 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

func init() {
	proto.RegisterType((*AlimamaProduct)(nil), "jarviscrawlercore.AlimamaProduct")
	proto.RegisterType((*AlimamaTopProduct)(nil), "jarviscrawlercore.AlimamaTopProduct")
	proto.RegisterType((*AlimamaTopInfo)(nil), "jarviscrawlercore.AlimamaTopInfo")
	proto.RegisterType((*AlimamaProducts)(nil), "jarviscrawlercore.AlimamaProducts")
	proto.RegisterType((*RequestAlimama)(nil), "jarviscrawlercore.RequestAlimama")
	proto.RegisterType((*ReplyAlimama)(nil), "jarviscrawlercore.ReplyAlimama")
	proto.RegisterEnum("jarviscrawlercore.AlimamaMode", AlimamaMode_name, AlimamaMode_value)
}

func init() { proto.RegisterFile("alimama.proto", fileDescriptor_alimama_5e1a65255b69148d) }

var fileDescriptor_alimama_5e1a65255b69148d = []byte{
	// 493 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x53, 0x4d, 0x6f, 0xd3, 0x40,
	0x10, 0x8d, 0x9d, 0xef, 0x71, 0x1b, 0x92, 0x15, 0x42, 0x2b, 0x84, 0x2a, 0xd7, 0xe2, 0x10, 0x71,
	0xc8, 0x21, 0x48, 0xdc, 0x2a, 0x11, 0xaa, 0x88, 0x44, 0x34, 0x22, 0x2c, 0x51, 0xc5, 0x0d, 0x6d,
	0xed, 0x25, 0x18, 0x79, 0xbd, 0x66, 0x77, 0x0d, 0xe4, 0x0f, 0x72, 0xe2, 0x47, 0xa1, 0x5d, 0xc7,
	0x1f, 0x15, 0x2a, 0x3d, 0xf4, 0x36, 0xf3, 0xf6, 0xcd, 0xcc, 0x9b, 0x79, 0x36, 0x9c, 0xd2, 0x24,
	0xe6, 0x94, 0xd3, 0x59, 0x26, 0x85, 0x16, 0x68, 0xf2, 0x8d, 0xca, 0x1f, 0xb1, 0x0a, 0x25, 0xfd,
	0x99, 0x30, 0x19, 0x0a, 0xc9, 0x82, 0xdf, 0x2e, 0x8c, 0x16, 0x05, 0x69, 0x2b, 0x45, 0x94, 0x87,
	0x1a, 0x21, 0xe8, 0xa4, 0x94, 0x33, 0xec, 0xf8, 0xce, 0x74, 0x48, 0x6c, 0x8c, 0xc6, 0xd0, 0xce,
	0x65, 0x82, 0x5d, 0x0b, 0x99, 0xd0, 0xb0, 0xd4, 0x57, 0x91, 0xe1, 0x76, 0xc1, 0x32, 0xb1, 0x61,
	0xc5, 0x7c, 0x8f, 0x3b, 0x05, 0x2b, 0xe6, 0x7b, 0x74, 0x06, 0x90, 0x50, 0xa5, 0x2f, 0x45, 0x9e,
	0x89, 0x14, 0x77, 0x7d, 0x67, 0xea, 0x92, 0x06, 0x82, 0x9e, 0xc2, 0x20, 0xcc, 0xe5, 0x56, 0xc6,
	0x21, 0xc3, 0x3d, 0xfb, 0x5a, 0xe5, 0xe8, 0x09, 0xf4, 0x24, 0xbb, 0xa1, 0x9a, 0xe1, 0xbe, 0x7d,
	0x39, 0x66, 0xa6, 0x67, 0x28, 0x38, 0x8f, 0x95, 0x8a, 0x45, 0x8a, 0x07, 0x45, 0xcf, 0x1a, 0x41,
	0xcf, 0x60, 0xc8, 0x45, 0xca, 0x0e, 0x1f, 0x72, 0x9a, 0xe2, 0xa1, 0x7d, 0xae, 0x01, 0x33, 0xd1,
	0x68, 0xdd, 0x1d, 0x32, 0x86, 0xc1, 0x0a, 0xad, 0x72, 0xe4, 0x83, 0xa7, 0x68, 0xc2, 0xd4, 0xb5,
	0x48, 0x72, 0xce, 0xb0, 0xe7, 0x3b, 0xd3, 0x2e, 0x69, 0x42, 0x08, 0x43, 0xdf, 0xb0, 0xcd, 0x2d,
	0x4e, 0x6c, 0x71, 0x99, 0x06, 0x29, 0x4c, 0x8e, 0x77, 0xdc, 0x89, 0xac, 0x3c, 0xa5, 0x59, 0x8f,
	0x6a, 0xb6, 0x17, 0xf2, 0x80, 0x1d, 0xbf, 0x6d, 0x86, 0x95, 0x39, 0xba, 0x80, 0x41, 0x56, 0xd0,
	0x14, 0x76, 0xfd, 0xf6, 0xd4, 0x9b, 0x9f, 0xcf, 0xfe, 0xf1, 0x67, 0x76, 0xdb, 0x1b, 0x52, 0x95,
	0x04, 0xab, 0xca, 0xb7, 0x9d, 0xc8, 0xd6, 0xe9, 0x17, 0x81, 0x5e, 0x41, 0x3b, 0x51, 0xda, 0xce,
	0xf1, 0xe6, 0xcf, 0xef, 0xee, 0x55, 0xeb, 0x23, 0xa6, 0x20, 0x88, 0xe0, 0xd1, 0xed, 0x29, 0xca,
	0x98, 0xab, 0xd9, 0x2f, 0x5d, 0x7e, 0x02, 0x26, 0x7e, 0xa8, 0xde, 0x4f, 0x30, 0x22, 0xec, 0x7b,
	0xce, 0x94, 0x3e, 0x52, 0xd0, 0x1c, 0x3a, 0x5c, 0x44, 0xc5, 0x77, 0x36, 0x9a, 0x9f, 0xdd, 0xdd,
	0x6c, 0x23, 0x22, 0x46, 0x2c, 0xb7, 0x12, 0xe6, 0xd6, 0xc2, 0x82, 0x3f, 0x0e, 0x9c, 0x10, 0x96,
	0x25, 0x87, 0x87, 0x34, 0x7e, 0xdd, 0xd8, 0x2e, 0xf2, 0x9d, 0xa9, 0x37, 0x0f, 0xee, 0xdd, 0x4e,
	0xad, 0x5a, 0xf5, 0x82, 0xe8, 0x02, 0xfa, 0xba, 0x70, 0x02, 0x33, 0xdb, 0xe0, 0xfc, 0xbf, 0x16,
	0x18, 0xe2, 0xaa, 0x45, 0xca, 0x9a, 0x37, 0x7d, 0xe8, 0x4a, 0xb3, 0xc4, 0x8b, 0x35, 0x78, 0x0d,
	0x79, 0xe8, 0x31, 0x8c, 0x17, 0x57, 0xeb, 0xcd, 0x66, 0xf3, 0xf9, 0xdd, 0x72, 0xb9, 0x5d, 0x5c,
	0xad, 0xaf, 0x97, 0xe3, 0x16, 0x9a, 0xc0, 0xe9, 0x11, 0xfd, 0xb8, 0x5c, 0x90, 0xcb, 0xd5, 0xd8,
	0x69, 0x40, 0x6f, 0x97, 0xbb, 0xdd, 0xfb, 0xed, 0xd8, 0xbd, 0xe9, 0xd9, 0xdf, 0xfe, 0xe5, 0xdf,
	0x00, 0x00, 0x00, 0xff, 0xff, 0xdf, 0x45, 0x97, 0x14, 0x07, 0x04, 0x00, 0x00,
}
