// Code generated by protoc-gen-go. DO NOT EDIT.
// source: mountainsteals.proto

package jarviscrawlercore

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// MountainStealsMode - mountain steals mode
type MountainStealsMode int32

const (
	// MSM_SALE - sale
	MountainStealsMode_MSM_SALE MountainStealsMode = 0
	// MSM_PRODUCT - product
	MountainStealsMode_MSM_PRODUCT MountainStealsMode = 1
)

var MountainStealsMode_name = map[int32]string{
	0: "MSM_SALE",
	1: "MSM_PRODUCT",
}
var MountainStealsMode_value = map[string]int32{
	"MSM_SALE":    0,
	"MSM_PRODUCT": 1,
}

func (x MountainStealsMode) String() string {
	return proto.EnumName(MountainStealsMode_name, int32(x))
}
func (MountainStealsMode) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_mountainsteals_2369ac8c24a4f7fa, []int{0}
}

// MountainStealsSale - mountain steals sale
type MountainStealsSale struct {
	Products             []string `protobuf:"bytes,1,rep,name=products,proto3" json:"products,omitempty"`
	Saleurl              string   `protobuf:"bytes,2,opt,name=saleurl,proto3" json:"saleurl,omitempty"`
	Code                 string   `protobuf:"bytes,3,opt,name=code,proto3" json:"code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MountainStealsSale) Reset()         { *m = MountainStealsSale{} }
func (m *MountainStealsSale) String() string { return proto.CompactTextString(m) }
func (*MountainStealsSale) ProtoMessage()    {}
func (*MountainStealsSale) Descriptor() ([]byte, []int) {
	return fileDescriptor_mountainsteals_2369ac8c24a4f7fa, []int{0}
}
func (m *MountainStealsSale) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MountainStealsSale.Unmarshal(m, b)
}
func (m *MountainStealsSale) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MountainStealsSale.Marshal(b, m, deterministic)
}
func (dst *MountainStealsSale) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MountainStealsSale.Merge(dst, src)
}
func (m *MountainStealsSale) XXX_Size() int {
	return xxx_messageInfo_MountainStealsSale.Size(m)
}
func (m *MountainStealsSale) XXX_DiscardUnknown() {
	xxx_messageInfo_MountainStealsSale.DiscardUnknown(m)
}

var xxx_messageInfo_MountainStealsSale proto.InternalMessageInfo

func (m *MountainStealsSale) GetProducts() []string {
	if m != nil {
		return m.Products
	}
	return nil
}

func (m *MountainStealsSale) GetSaleurl() string {
	if m != nil {
		return m.Saleurl
	}
	return ""
}

func (m *MountainStealsSale) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

// MountainStealsColorSize - mountain steals color size
type MountainStealsColorSize struct {
	Color                string   `protobuf:"bytes,1,opt,name=color,proto3" json:"color,omitempty"`
	Size                 string   `protobuf:"bytes,2,opt,name=size,proto3" json:"size,omitempty"`
	Price                float32  `protobuf:"fixed32,3,opt,name=price,proto3" json:"price,omitempty"`
	Img                  string   `protobuf:"bytes,4,opt,name=img,proto3" json:"img,omitempty"`
	Sku                  string   `protobuf:"bytes,5,opt,name=sku,proto3" json:"sku,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MountainStealsColorSize) Reset()         { *m = MountainStealsColorSize{} }
func (m *MountainStealsColorSize) String() string { return proto.CompactTextString(m) }
func (*MountainStealsColorSize) ProtoMessage()    {}
func (*MountainStealsColorSize) Descriptor() ([]byte, []int) {
	return fileDescriptor_mountainsteals_2369ac8c24a4f7fa, []int{1}
}
func (m *MountainStealsColorSize) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MountainStealsColorSize.Unmarshal(m, b)
}
func (m *MountainStealsColorSize) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MountainStealsColorSize.Marshal(b, m, deterministic)
}
func (dst *MountainStealsColorSize) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MountainStealsColorSize.Merge(dst, src)
}
func (m *MountainStealsColorSize) XXX_Size() int {
	return xxx_messageInfo_MountainStealsColorSize.Size(m)
}
func (m *MountainStealsColorSize) XXX_DiscardUnknown() {
	xxx_messageInfo_MountainStealsColorSize.DiscardUnknown(m)
}

var xxx_messageInfo_MountainStealsColorSize proto.InternalMessageInfo

func (m *MountainStealsColorSize) GetColor() string {
	if m != nil {
		return m.Color
	}
	return ""
}

func (m *MountainStealsColorSize) GetSize() string {
	if m != nil {
		return m.Size
	}
	return ""
}

func (m *MountainStealsColorSize) GetPrice() float32 {
	if m != nil {
		return m.Price
	}
	return 0
}

func (m *MountainStealsColorSize) GetImg() string {
	if m != nil {
		return m.Img
	}
	return ""
}

func (m *MountainStealsColorSize) GetSku() string {
	if m != nil {
		return m.Sku
	}
	return ""
}

// MountainStealsProduct - mountain steals product
type MountainStealsProduct struct {
	Code                 string                     `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Name                 string                     `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Category             []string                   `protobuf:"bytes,3,rep,name=category,proto3" json:"category,omitempty"`
	Brand                string                     `protobuf:"bytes,4,opt,name=brand,proto3" json:"brand,omitempty"`
	Rating               float32                    `protobuf:"fixed32,5,opt,name=rating,proto3" json:"rating,omitempty"`
	ColorSize            []*MountainStealsColorSize `protobuf:"bytes,6,rep,name=colorSize,proto3" json:"colorSize,omitempty"`
	Images               []string                   `protobuf:"bytes,7,rep,name=images,proto3" json:"images,omitempty"`
	Price                float32                    `protobuf:"fixed32,8,opt,name=price,proto3" json:"price,omitempty"`
	MinPrice             float32                    `protobuf:"fixed32,9,opt,name=minPrice,proto3" json:"minPrice,omitempty"`
	MaxPrice             float32                    `protobuf:"fixed32,10,opt,name=maxPrice,proto3" json:"maxPrice,omitempty"`
	Details              string                     `protobuf:"bytes,11,opt,name=details,proto3" json:"details,omitempty"`
	Spec                 string                     `protobuf:"bytes,12,opt,name=spec,proto3" json:"spec,omitempty"`
	RatingCount          []int32                    `protobuf:"varint,13,rep,packed,name=ratingCount,proto3" json:"ratingCount,omitempty"`
	MapRading            map[string]float32         `protobuf:"bytes,14,rep,name=mapRading,proto3" json:"mapRading,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"fixed32,2,opt,name=value,proto3"`
	SizeGiud             string                     `protobuf:"bytes,15,opt,name=sizeGiud,proto3" json:"sizeGiud,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                   `json:"-"`
	XXX_unrecognized     []byte                     `json:"-"`
	XXX_sizecache        int32                      `json:"-"`
}

func (m *MountainStealsProduct) Reset()         { *m = MountainStealsProduct{} }
func (m *MountainStealsProduct) String() string { return proto.CompactTextString(m) }
func (*MountainStealsProduct) ProtoMessage()    {}
func (*MountainStealsProduct) Descriptor() ([]byte, []int) {
	return fileDescriptor_mountainsteals_2369ac8c24a4f7fa, []int{2}
}
func (m *MountainStealsProduct) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MountainStealsProduct.Unmarshal(m, b)
}
func (m *MountainStealsProduct) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MountainStealsProduct.Marshal(b, m, deterministic)
}
func (dst *MountainStealsProduct) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MountainStealsProduct.Merge(dst, src)
}
func (m *MountainStealsProduct) XXX_Size() int {
	return xxx_messageInfo_MountainStealsProduct.Size(m)
}
func (m *MountainStealsProduct) XXX_DiscardUnknown() {
	xxx_messageInfo_MountainStealsProduct.DiscardUnknown(m)
}

var xxx_messageInfo_MountainStealsProduct proto.InternalMessageInfo

func (m *MountainStealsProduct) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *MountainStealsProduct) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *MountainStealsProduct) GetCategory() []string {
	if m != nil {
		return m.Category
	}
	return nil
}

func (m *MountainStealsProduct) GetBrand() string {
	if m != nil {
		return m.Brand
	}
	return ""
}

func (m *MountainStealsProduct) GetRating() float32 {
	if m != nil {
		return m.Rating
	}
	return 0
}

func (m *MountainStealsProduct) GetColorSize() []*MountainStealsColorSize {
	if m != nil {
		return m.ColorSize
	}
	return nil
}

func (m *MountainStealsProduct) GetImages() []string {
	if m != nil {
		return m.Images
	}
	return nil
}

func (m *MountainStealsProduct) GetPrice() float32 {
	if m != nil {
		return m.Price
	}
	return 0
}

func (m *MountainStealsProduct) GetMinPrice() float32 {
	if m != nil {
		return m.MinPrice
	}
	return 0
}

func (m *MountainStealsProduct) GetMaxPrice() float32 {
	if m != nil {
		return m.MaxPrice
	}
	return 0
}

func (m *MountainStealsProduct) GetDetails() string {
	if m != nil {
		return m.Details
	}
	return ""
}

func (m *MountainStealsProduct) GetSpec() string {
	if m != nil {
		return m.Spec
	}
	return ""
}

func (m *MountainStealsProduct) GetRatingCount() []int32 {
	if m != nil {
		return m.RatingCount
	}
	return nil
}

func (m *MountainStealsProduct) GetMapRading() map[string]float32 {
	if m != nil {
		return m.MapRading
	}
	return nil
}

func (m *MountainStealsProduct) GetSizeGiud() string {
	if m != nil {
		return m.SizeGiud
	}
	return ""
}

// RequestMountainSteals - request mountain steals
type RequestMountainSteals struct {
	Mode                 MountainStealsMode `protobuf:"varint,1,opt,name=mode,proto3,enum=jarviscrawlercore.MountainStealsMode" json:"mode,omitempty"`
	Url                  string             `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *RequestMountainSteals) Reset()         { *m = RequestMountainSteals{} }
func (m *RequestMountainSteals) String() string { return proto.CompactTextString(m) }
func (*RequestMountainSteals) ProtoMessage()    {}
func (*RequestMountainSteals) Descriptor() ([]byte, []int) {
	return fileDescriptor_mountainsteals_2369ac8c24a4f7fa, []int{3}
}
func (m *RequestMountainSteals) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RequestMountainSteals.Unmarshal(m, b)
}
func (m *RequestMountainSteals) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RequestMountainSteals.Marshal(b, m, deterministic)
}
func (dst *RequestMountainSteals) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RequestMountainSteals.Merge(dst, src)
}
func (m *RequestMountainSteals) XXX_Size() int {
	return xxx_messageInfo_RequestMountainSteals.Size(m)
}
func (m *RequestMountainSteals) XXX_DiscardUnknown() {
	xxx_messageInfo_RequestMountainSteals.DiscardUnknown(m)
}

var xxx_messageInfo_RequestMountainSteals proto.InternalMessageInfo

func (m *RequestMountainSteals) GetMode() MountainStealsMode {
	if m != nil {
		return m.Mode
	}
	return MountainStealsMode_MSM_SALE
}

func (m *RequestMountainSteals) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

// ReplyMountainSteals - reply mountain steals
type ReplyMountainSteals struct {
	Mode MountainStealsMode `protobuf:"varint,1,opt,name=mode,proto3,enum=jarviscrawlercore.MountainStealsMode" json:"mode,omitempty"`
	// Types that are valid to be assigned to Reply:
	//	*ReplyMountainSteals_Sale
	//	*ReplyMountainSteals_Product
	Reply                isReplyMountainSteals_Reply `protobuf_oneof:"reply"`
	XXX_NoUnkeyedLiteral struct{}                    `json:"-"`
	XXX_unrecognized     []byte                      `json:"-"`
	XXX_sizecache        int32                       `json:"-"`
}

func (m *ReplyMountainSteals) Reset()         { *m = ReplyMountainSteals{} }
func (m *ReplyMountainSteals) String() string { return proto.CompactTextString(m) }
func (*ReplyMountainSteals) ProtoMessage()    {}
func (*ReplyMountainSteals) Descriptor() ([]byte, []int) {
	return fileDescriptor_mountainsteals_2369ac8c24a4f7fa, []int{4}
}
func (m *ReplyMountainSteals) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReplyMountainSteals.Unmarshal(m, b)
}
func (m *ReplyMountainSteals) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReplyMountainSteals.Marshal(b, m, deterministic)
}
func (dst *ReplyMountainSteals) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReplyMountainSteals.Merge(dst, src)
}
func (m *ReplyMountainSteals) XXX_Size() int {
	return xxx_messageInfo_ReplyMountainSteals.Size(m)
}
func (m *ReplyMountainSteals) XXX_DiscardUnknown() {
	xxx_messageInfo_ReplyMountainSteals.DiscardUnknown(m)
}

var xxx_messageInfo_ReplyMountainSteals proto.InternalMessageInfo

type isReplyMountainSteals_Reply interface {
	isReplyMountainSteals_Reply()
}

type ReplyMountainSteals_Sale struct {
	Sale *MountainStealsSale `protobuf:"bytes,100,opt,name=sale,proto3,oneof"`
}
type ReplyMountainSteals_Product struct {
	Product *MountainStealsProduct `protobuf:"bytes,101,opt,name=product,proto3,oneof"`
}

func (*ReplyMountainSteals_Sale) isReplyMountainSteals_Reply()    {}
func (*ReplyMountainSteals_Product) isReplyMountainSteals_Reply() {}

func (m *ReplyMountainSteals) GetReply() isReplyMountainSteals_Reply {
	if m != nil {
		return m.Reply
	}
	return nil
}

func (m *ReplyMountainSteals) GetMode() MountainStealsMode {
	if m != nil {
		return m.Mode
	}
	return MountainStealsMode_MSM_SALE
}

func (m *ReplyMountainSteals) GetSale() *MountainStealsSale {
	if x, ok := m.GetReply().(*ReplyMountainSteals_Sale); ok {
		return x.Sale
	}
	return nil
}

func (m *ReplyMountainSteals) GetProduct() *MountainStealsProduct {
	if x, ok := m.GetReply().(*ReplyMountainSteals_Product); ok {
		return x.Product
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*ReplyMountainSteals) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _ReplyMountainSteals_OneofMarshaler, _ReplyMountainSteals_OneofUnmarshaler, _ReplyMountainSteals_OneofSizer, []interface{}{
		(*ReplyMountainSteals_Sale)(nil),
		(*ReplyMountainSteals_Product)(nil),
	}
}

func _ReplyMountainSteals_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*ReplyMountainSteals)
	// reply
	switch x := m.Reply.(type) {
	case *ReplyMountainSteals_Sale:
		b.EncodeVarint(100<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Sale); err != nil {
			return err
		}
	case *ReplyMountainSteals_Product:
		b.EncodeVarint(101<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Product); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("ReplyMountainSteals.Reply has unexpected type %T", x)
	}
	return nil
}

func _ReplyMountainSteals_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*ReplyMountainSteals)
	switch tag {
	case 100: // reply.sale
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(MountainStealsSale)
		err := b.DecodeMessage(msg)
		m.Reply = &ReplyMountainSteals_Sale{msg}
		return true, err
	case 101: // reply.product
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(MountainStealsProduct)
		err := b.DecodeMessage(msg)
		m.Reply = &ReplyMountainSteals_Product{msg}
		return true, err
	default:
		return false, nil
	}
}

func _ReplyMountainSteals_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*ReplyMountainSteals)
	// reply
	switch x := m.Reply.(type) {
	case *ReplyMountainSteals_Sale:
		s := proto.Size(x.Sale)
		n += 2 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *ReplyMountainSteals_Product:
		s := proto.Size(x.Product)
		n += 2 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

func init() {
	proto.RegisterType((*MountainStealsSale)(nil), "jarviscrawlercore.MountainStealsSale")
	proto.RegisterType((*MountainStealsColorSize)(nil), "jarviscrawlercore.MountainStealsColorSize")
	proto.RegisterType((*MountainStealsProduct)(nil), "jarviscrawlercore.MountainStealsProduct")
	proto.RegisterMapType((map[string]float32)(nil), "jarviscrawlercore.MountainStealsProduct.MapRadingEntry")
	proto.RegisterType((*RequestMountainSteals)(nil), "jarviscrawlercore.RequestMountainSteals")
	proto.RegisterType((*ReplyMountainSteals)(nil), "jarviscrawlercore.ReplyMountainSteals")
	proto.RegisterEnum("jarviscrawlercore.MountainStealsMode", MountainStealsMode_name, MountainStealsMode_value)
}

func init() {
	proto.RegisterFile("mountainsteals.proto", fileDescriptor_mountainsteals_2369ac8c24a4f7fa)
}

var fileDescriptor_mountainsteals_2369ac8c24a4f7fa = []byte{
	// 559 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x54, 0xcd, 0x6e, 0xd3, 0x40,
	0x10, 0xae, 0xe3, 0xa4, 0x49, 0x26, 0x25, 0x0d, 0x4b, 0x0b, 0xab, 0x9c, 0xac, 0x48, 0x48, 0x56,
	0x0f, 0x39, 0xb4, 0x07, 0x7e, 0x2f, 0x90, 0x56, 0xe4, 0x40, 0x44, 0xb4, 0xa1, 0x57, 0xd0, 0xd6,
	0x5e, 0x45, 0x4b, 0xfc, 0xc7, 0xae, 0x5d, 0x48, 0x25, 0x5e, 0x8c, 0x67, 0xe1, 0x61, 0xd0, 0xec,
	0xae, 0x93, 0x06, 0x84, 0xda, 0x03, 0xb7, 0xf9, 0xe6, 0xf7, 0x9b, 0xf9, 0xbc, 0x86, 0xa3, 0x34,
	0xaf, 0xb2, 0x92, 0xcb, 0x4c, 0x97, 0x82, 0x27, 0x7a, 0x5c, 0xa8, 0xbc, 0xcc, 0xc9, 0xc3, 0x2f,
	0x5c, 0x5d, 0x4b, 0x1d, 0x29, 0xfe, 0x2d, 0x11, 0x2a, 0xca, 0x95, 0x18, 0x7d, 0x02, 0x32, 0x73,
	0xa9, 0x0b, 0x93, 0xba, 0xe0, 0x89, 0x20, 0x43, 0xe8, 0x14, 0x2a, 0x8f, 0xab, 0xa8, 0xd4, 0xd4,
	0x0b, 0xfc, 0xb0, 0xcb, 0x36, 0x98, 0x50, 0x68, 0x6b, 0x9e, 0x88, 0x4a, 0x25, 0xb4, 0x11, 0x78,
	0x61, 0x97, 0xd5, 0x90, 0x10, 0x68, 0x46, 0x79, 0x2c, 0xa8, 0x6f, 0xdc, 0xc6, 0x1e, 0xfd, 0x80,
	0x27, 0xbb, 0xfd, 0x27, 0x79, 0x92, 0xab, 0x85, 0xbc, 0x11, 0xe4, 0x08, 0x5a, 0x11, 0x02, 0xea,
	0x99, 0x7c, 0x0b, 0xb0, 0x89, 0x96, 0x37, 0xc2, 0xf5, 0x36, 0x36, 0x66, 0x16, 0x4a, 0x46, 0xb6,
	0x73, 0x83, 0x59, 0x40, 0x06, 0xe0, 0xcb, 0x74, 0x49, 0x9b, 0x26, 0x11, 0x4d, 0xf4, 0xe8, 0x55,
	0x45, 0x5b, 0xd6, 0xa3, 0x57, 0xd5, 0xe8, 0x67, 0x13, 0x8e, 0x77, 0xe7, 0xcf, 0xed, 0x1e, 0x1b,
	0xb2, 0xde, 0x96, 0x2c, 0xfa, 0x32, 0x9e, 0x6e, 0x66, 0xa3, 0x8d, 0xa7, 0x88, 0x78, 0x29, 0x96,
	0xb9, 0x5a, 0x53, 0xdf, 0x9e, 0xa2, 0xc6, 0xc8, 0xeb, 0x4a, 0xf1, 0x2c, 0x76, 0x1c, 0x2c, 0x20,
	0x8f, 0x61, 0x5f, 0xf1, 0x52, 0x66, 0x4b, 0x43, 0xa4, 0xc1, 0x1c, 0x22, 0x53, 0xe8, 0x46, 0xf5,
	0xf2, 0x74, 0x3f, 0xf0, 0xc3, 0xde, 0xe9, 0xc9, 0xf8, 0x2f, 0x45, 0xc6, 0xff, 0x38, 0x17, 0xdb,
	0x16, 0xe3, 0x04, 0x99, 0xf2, 0xa5, 0xd0, 0xb4, 0x6d, 0x18, 0x39, 0xb4, 0xbd, 0x53, 0xe7, 0xf6,
	0x9d, 0x86, 0xd0, 0x49, 0x65, 0x36, 0x37, 0x81, 0xae, 0x09, 0x6c, 0xb0, 0x89, 0xf1, 0xef, 0x36,
	0x06, 0x2e, 0xe6, 0x30, 0x0a, 0x1d, 0x8b, 0x92, 0xcb, 0x44, 0xd3, 0x9e, 0x15, 0xda, 0x41, 0xa3,
	0x51, 0x21, 0x22, 0x7a, 0xe0, 0x34, 0x2a, 0x44, 0x44, 0x02, 0xe8, 0xd9, 0x3d, 0x27, 0xc8, 0x9f,
	0x3e, 0x08, 0xfc, 0xb0, 0xc5, 0x6e, 0xbb, 0xc8, 0x25, 0x74, 0x53, 0x5e, 0x30, 0x1e, 0xe3, 0x69,
	0xfa, 0x66, 0xff, 0x67, 0x77, 0xee, 0xef, 0xe4, 0x1a, 0xcf, 0xea, 0xca, 0x8b, 0xac, 0x54, 0x6b,
	0xb6, 0xed, 0x84, 0x2b, 0xe0, 0x47, 0xf2, 0x4e, 0x56, 0x31, 0x3d, 0x34, 0x84, 0x36, 0x78, 0xf8,
	0x1a, 0xfa, 0xbb, 0x85, 0xf8, 0x89, 0xac, 0xc4, 0xda, 0xa9, 0x8e, 0x26, 0x1e, 0xed, 0x9a, 0x27,
	0x95, 0x55, 0xbd, 0xc1, 0x2c, 0x78, 0xd9, 0x78, 0xee, 0x8d, 0x62, 0x38, 0x66, 0xe2, 0x6b, 0x25,
	0x74, 0xb9, 0xcb, 0x89, 0xbc, 0x80, 0x66, 0x5a, 0x7f, 0x3b, 0xfd, 0xd3, 0xa7, 0x77, 0x2e, 0x31,
	0xcb, 0x63, 0xc1, 0x4c, 0x09, 0xce, 0xdf, 0xbe, 0x1c, 0x34, 0x47, 0xbf, 0x3c, 0x78, 0xc4, 0x44,
	0x91, 0xac, 0xff, 0xdf, 0x90, 0x57, 0xd0, 0xc4, 0x37, 0x49, 0xe3, 0xc0, 0x0b, 0x7b, 0xf7, 0x28,
	0xc5, 0x37, 0x3f, 0xdd, 0x63, 0xa6, 0x88, 0x9c, 0x43, 0xdb, 0xbd, 0x75, 0x2a, 0x4c, 0x7d, 0x78,
	0x5f, 0x91, 0xa6, 0x7b, 0xac, 0x2e, 0x7d, 0xdb, 0x86, 0x96, 0xc2, 0xa5, 0x4e, 0xce, 0xfe, 0xfc,
	0xc1, 0x20, 0x4f, 0x72, 0x00, 0x9d, 0xd9, 0x62, 0xf6, 0x79, 0xf1, 0xe6, 0xfd, 0xc5, 0x60, 0x8f,
	0x1c, 0x42, 0x0f, 0xd1, 0x9c, 0x7d, 0x38, 0xbf, 0x9c, 0x7c, 0x1c, 0x78, 0x57, 0xfb, 0xe6, 0x7f,
	0x75, 0xf6, 0x3b, 0x00, 0x00, 0xff, 0xff, 0x9a, 0x5c, 0x50, 0x0c, 0xc7, 0x04, 0x00, 0x00,
}
