// Code generated by protoc-gen-go. DO NOT EDIT.
// source: searchparam2.proto

package jarviscrawlercore

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// SearchParam2Type - SearchParam2Type
type SearchParam2Type int32

const (
	// SP2T_None - none
	SearchParam2Type_SP2T_None SearchParam2Type = 0
	// SP2T_And - and
	SearchParam2Type_SP2T_And SearchParam2Type = 1
	// SP2T_Or - or
	SearchParam2Type_SP2T_Or SearchParam2Type = 2
	// SP2T_Exclude - exclude
	SearchParam2Type_SP2T_Exclude SearchParam2Type = 3
	// SP2T_Combination - combination
	SearchParam2Type_SP2T_Combination SearchParam2Type = 4
)

var SearchParam2Type_name = map[int32]string{
	0: "SP2T_None",
	1: "SP2T_And",
	2: "SP2T_Or",
	3: "SP2T_Exclude",
	4: "SP2T_Combination",
}
var SearchParam2Type_value = map[string]int32{
	"SP2T_None":        0,
	"SP2T_And":         1,
	"SP2T_Or":          2,
	"SP2T_Exclude":     3,
	"SP2T_Combination": 4,
}

func (x SearchParam2Type) String() string {
	return proto.EnumName(SearchParam2Type_name, int32(x))
}
func (SearchParam2Type) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_searchparam2_1d61c0f0fd071bd3, []int{0}
}

// SearchParam2 - Search Param v2
type SearchParam2 struct {
	Text                 string           `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	Type                 SearchParam2Type `protobuf:"varint,2,opt,name=type,proto3,enum=jarviscrawlercore.SearchParam2Type" json:"type,omitempty"`
	ChildType            SearchParam2Type `protobuf:"varint,3,opt,name=childType,proto3,enum=jarviscrawlercore.SearchParam2Type" json:"childType,omitempty"`
	Children             []*SearchParam2  `protobuf:"bytes,4,rep,name=children,proto3" json:"children,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *SearchParam2) Reset()         { *m = SearchParam2{} }
func (m *SearchParam2) String() string { return proto.CompactTextString(m) }
func (*SearchParam2) ProtoMessage()    {}
func (*SearchParam2) Descriptor() ([]byte, []int) {
	return fileDescriptor_searchparam2_1d61c0f0fd071bd3, []int{0}
}
func (m *SearchParam2) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SearchParam2.Unmarshal(m, b)
}
func (m *SearchParam2) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SearchParam2.Marshal(b, m, deterministic)
}
func (dst *SearchParam2) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SearchParam2.Merge(dst, src)
}
func (m *SearchParam2) XXX_Size() int {
	return xxx_messageInfo_SearchParam2.Size(m)
}
func (m *SearchParam2) XXX_DiscardUnknown() {
	xxx_messageInfo_SearchParam2.DiscardUnknown(m)
}

var xxx_messageInfo_SearchParam2 proto.InternalMessageInfo

func (m *SearchParam2) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

func (m *SearchParam2) GetType() SearchParam2Type {
	if m != nil {
		return m.Type
	}
	return SearchParam2Type_SP2T_None
}

func (m *SearchParam2) GetChildType() SearchParam2Type {
	if m != nil {
		return m.ChildType
	}
	return SearchParam2Type_SP2T_None
}

func (m *SearchParam2) GetChildren() []*SearchParam2 {
	if m != nil {
		return m.Children
	}
	return nil
}

func init() {
	proto.RegisterType((*SearchParam2)(nil), "jarviscrawlercore.SearchParam2")
	proto.RegisterEnum("jarviscrawlercore.SearchParam2Type", SearchParam2Type_name, SearchParam2Type_value)
}

func init() { proto.RegisterFile("searchparam2.proto", fileDescriptor_searchparam2_1d61c0f0fd071bd3) }

var fileDescriptor_searchparam2_1d61c0f0fd071bd3 = []byte{
	// 236 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x90, 0x31, 0x4f, 0xc3, 0x30,
	0x10, 0x46, 0x71, 0x13, 0x41, 0x73, 0x0d, 0xc8, 0x9c, 0x18, 0xb2, 0x11, 0xc1, 0x12, 0x31, 0x64,
	0x08, 0x03, 0x03, 0x53, 0x85, 0x58, 0xa1, 0x4a, 0xbb, 0x23, 0xd7, 0x39, 0xa9, 0x41, 0xa9, 0x6d,
	0x5d, 0x0d, 0xb4, 0xbf, 0x95, 0x3f, 0x83, 0xb8, 0x01, 0x10, 0x0c, 0x74, 0xf3, 0x3b, 0x7d, 0xef,
	0x0d, 0x06, 0xdc, 0x90, 0x61, 0xbb, 0x0a, 0x86, 0xcd, 0xba, 0xa9, 0x03, 0xfb, 0xe8, 0xf1, 0xf4,
	0xd9, 0xf0, 0x6b, 0xbf, 0xb1, 0x6c, 0xde, 0x06, 0x62, 0xeb, 0x99, 0x2e, 0xde, 0x15, 0xe4, 0x73,
	0x59, 0xce, 0x64, 0x89, 0x08, 0x69, 0xa4, 0x6d, 0x2c, 0x54, 0xa9, 0xaa, 0xac, 0x95, 0x37, 0xde,
	0x40, 0x1a, 0x77, 0x81, 0x8a, 0x51, 0xa9, 0xaa, 0x93, 0xe6, 0xb2, 0xfe, 0x93, 0xa9, 0x7f, 0x26,
	0x16, 0xbb, 0x40, 0xad, 0x08, 0x38, 0x85, 0xcc, 0xae, 0xfa, 0xa1, 0xfb, 0x3c, 0x15, 0xc9, 0xfe,
	0xf6, 0xb7, 0x85, 0xb7, 0x30, 0x16, 0x60, 0x72, 0x45, 0x5a, 0x26, 0xd5, 0xa4, 0x39, 0xff, 0xa7,
	0xd0, 0x7e, 0x09, 0x57, 0x1d, 0xe8, 0xdf, 0x6d, 0x3c, 0x86, 0x6c, 0x3e, 0x6b, 0x16, 0x4f, 0x0f,
	0xde, 0x91, 0x3e, 0xc0, 0x1c, 0xc6, 0x82, 0x53, 0xd7, 0x69, 0x85, 0x13, 0x38, 0x12, 0x7a, 0x64,
	0x3d, 0x42, 0x0d, 0xb9, 0xc0, 0xfd, 0xd6, 0x0e, 0x2f, 0x1d, 0xe9, 0x04, 0xcf, 0x40, 0xcb, 0xe5,
	0xce, 0xaf, 0x97, 0xbd, 0x33, 0xb1, 0xf7, 0x4e, 0xa7, 0xcb, 0x43, 0xf9, 0xdd, 0xeb, 0x8f, 0x00,
	0x00, 0x00, 0xff, 0xff, 0xb6, 0x71, 0xee, 0x31, 0x73, 0x01, 0x00, 0x00,
}
