// Code generated by protoc-gen-go. DO NOT EDIT.
// source: taobao.proto

package jarviscrawlercore

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// TaobaoMode - taobao mode
type TaobaoMode int32

const (
	// TBM_PRODUCT - product
	TaobaoMode_TBM_PRODUCT TaobaoMode = 0
	// TBM_SEARCH - search
	TaobaoMode_TBM_SEARCH TaobaoMode = 1
	// TBM_MOBILEPRODUCT - mobile product
	TaobaoMode_TBM_MOBILEPRODUCT TaobaoMode = 2
)

var TaobaoMode_name = map[int32]string{
	0: "TBM_PRODUCT",
	1: "TBM_SEARCH",
	2: "TBM_MOBILEPRODUCT",
}
var TaobaoMode_value = map[string]int32{
	"TBM_PRODUCT":       0,
	"TBM_SEARCH":        1,
	"TBM_MOBILEPRODUCT": 2,
}

func (x TaobaoMode) String() string {
	return proto.EnumName(TaobaoMode_name, int32(x))
}
func (TaobaoMode) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_taobao_8dc4eb4fd83dc173, []int{0}
}

// TaobaoSKUInfo - taobao sku infomation
type TaobaoSKUInfo struct {
	Skuid                string   `protobuf:"bytes,1,opt,name=skuid,proto3" json:"skuid,omitempty"`
	Price                float32  `protobuf:"fixed32,2,opt,name=price,proto3" json:"price,omitempty"`
	Title                string   `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Img                  string   `protobuf:"bytes,4,opt,name=img,proto3" json:"img,omitempty"`
	Stock                int32    `protobuf:"varint,5,opt,name=stock,proto3" json:"stock,omitempty"`
	Valueid              string   `protobuf:"bytes,6,opt,name=valueid,proto3" json:"valueid,omitempty"`
	Itemid               string   `protobuf:"bytes,7,opt,name=itemid,proto3" json:"itemid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TaobaoSKUInfo) Reset()         { *m = TaobaoSKUInfo{} }
func (m *TaobaoSKUInfo) String() string { return proto.CompactTextString(m) }
func (*TaobaoSKUInfo) ProtoMessage()    {}
func (*TaobaoSKUInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_taobao_8dc4eb4fd83dc173, []int{0}
}
func (m *TaobaoSKUInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TaobaoSKUInfo.Unmarshal(m, b)
}
func (m *TaobaoSKUInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TaobaoSKUInfo.Marshal(b, m, deterministic)
}
func (dst *TaobaoSKUInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TaobaoSKUInfo.Merge(dst, src)
}
func (m *TaobaoSKUInfo) XXX_Size() int {
	return xxx_messageInfo_TaobaoSKUInfo.Size(m)
}
func (m *TaobaoSKUInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_TaobaoSKUInfo.DiscardUnknown(m)
}

var xxx_messageInfo_TaobaoSKUInfo proto.InternalMessageInfo

func (m *TaobaoSKUInfo) GetSkuid() string {
	if m != nil {
		return m.Skuid
	}
	return ""
}

func (m *TaobaoSKUInfo) GetPrice() float32 {
	if m != nil {
		return m.Price
	}
	return 0
}

func (m *TaobaoSKUInfo) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *TaobaoSKUInfo) GetImg() string {
	if m != nil {
		return m.Img
	}
	return ""
}

func (m *TaobaoSKUInfo) GetStock() int32 {
	if m != nil {
		return m.Stock
	}
	return 0
}

func (m *TaobaoSKUInfo) GetValueid() string {
	if m != nil {
		return m.Valueid
	}
	return ""
}

func (m *TaobaoSKUInfo) GetItemid() string {
	if m != nil {
		return m.Itemid
	}
	return ""
}

// TaobaoShopInfo - taobao shop infomation
type TaobaoShopInfo struct {
	Name                 string    `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Gold                 bool      `protobuf:"varint,2,opt,name=gold,proto3" json:"gold,omitempty"`
	Url                  string    `protobuf:"bytes,3,opt,name=url,proto3" json:"url,omitempty"`
	Rank                 string    `protobuf:"bytes,4,opt,name=rank,proto3" json:"rank,omitempty"`
	Rating               int32     `protobuf:"varint,5,opt,name=rating,proto3" json:"rating,omitempty"`
	RateLevel            []int32   `protobuf:"varint,6,rep,packed,name=rateLevel,proto3" json:"rateLevel,omitempty"`
	RateScore            []float32 `protobuf:"fixed32,7,rep,packed,name=rateScore,proto3" json:"rateScore,omitempty"`
	Shopid               string    `protobuf:"bytes,8,opt,name=shopid,proto3" json:"shopid,omitempty"`
	Userid               string    `protobuf:"bytes,9,opt,name=userid,proto3" json:"userid,omitempty"`
	CreditLevel          int32     `protobuf:"varint,10,opt,name=creditLevel,proto3" json:"creditLevel,omitempty"`
	AllItemCount         int32     `protobuf:"varint,11,opt,name=allItemCount,proto3" json:"allItemCount,omitempty"`
	NewItemCount         int32     `protobuf:"varint,12,opt,name=newItemCount,proto3" json:"newItemCount,omitempty"`
	StrFans              string    `protobuf:"bytes,13,opt,name=strFans,proto3" json:"strFans,omitempty"`
	GoodRatePercentage   float32   `protobuf:"fixed32,14,opt,name=goodRatePercentage,proto3" json:"goodRatePercentage,omitempty"`
	RateOffset           []float32 `protobuf:"fixed32,15,rep,packed,name=rateOffset,proto3" json:"rateOffset,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *TaobaoShopInfo) Reset()         { *m = TaobaoShopInfo{} }
func (m *TaobaoShopInfo) String() string { return proto.CompactTextString(m) }
func (*TaobaoShopInfo) ProtoMessage()    {}
func (*TaobaoShopInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_taobao_8dc4eb4fd83dc173, []int{1}
}
func (m *TaobaoShopInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TaobaoShopInfo.Unmarshal(m, b)
}
func (m *TaobaoShopInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TaobaoShopInfo.Marshal(b, m, deterministic)
}
func (dst *TaobaoShopInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TaobaoShopInfo.Merge(dst, src)
}
func (m *TaobaoShopInfo) XXX_Size() int {
	return xxx_messageInfo_TaobaoShopInfo.Size(m)
}
func (m *TaobaoShopInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_TaobaoShopInfo.DiscardUnknown(m)
}

var xxx_messageInfo_TaobaoShopInfo proto.InternalMessageInfo

func (m *TaobaoShopInfo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *TaobaoShopInfo) GetGold() bool {
	if m != nil {
		return m.Gold
	}
	return false
}

func (m *TaobaoShopInfo) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *TaobaoShopInfo) GetRank() string {
	if m != nil {
		return m.Rank
	}
	return ""
}

func (m *TaobaoShopInfo) GetRating() int32 {
	if m != nil {
		return m.Rating
	}
	return 0
}

func (m *TaobaoShopInfo) GetRateLevel() []int32 {
	if m != nil {
		return m.RateLevel
	}
	return nil
}

func (m *TaobaoShopInfo) GetRateScore() []float32 {
	if m != nil {
		return m.RateScore
	}
	return nil
}

func (m *TaobaoShopInfo) GetShopid() string {
	if m != nil {
		return m.Shopid
	}
	return ""
}

func (m *TaobaoShopInfo) GetUserid() string {
	if m != nil {
		return m.Userid
	}
	return ""
}

func (m *TaobaoShopInfo) GetCreditLevel() int32 {
	if m != nil {
		return m.CreditLevel
	}
	return 0
}

func (m *TaobaoShopInfo) GetAllItemCount() int32 {
	if m != nil {
		return m.AllItemCount
	}
	return 0
}

func (m *TaobaoShopInfo) GetNewItemCount() int32 {
	if m != nil {
		return m.NewItemCount
	}
	return 0
}

func (m *TaobaoShopInfo) GetStrFans() string {
	if m != nil {
		return m.StrFans
	}
	return ""
}

func (m *TaobaoShopInfo) GetGoodRatePercentage() float32 {
	if m != nil {
		return m.GoodRatePercentage
	}
	return 0
}

func (m *TaobaoShopInfo) GetRateOffset() []float32 {
	if m != nil {
		return m.RateOffset
	}
	return nil
}

// TaobaoProductHistory - taobao product history
type TaobaoProductHistory struct {
	Skus                 []*TaobaoSKUInfo `protobuf:"bytes,1,rep,name=skus,proto3" json:"skus,omitempty"`
	LastUpdatedTime      int64            `protobuf:"varint,2,opt,name=lastUpdatedTime,proto3" json:"lastUpdatedTime,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *TaobaoProductHistory) Reset()         { *m = TaobaoProductHistory{} }
func (m *TaobaoProductHistory) String() string { return proto.CompactTextString(m) }
func (*TaobaoProductHistory) ProtoMessage()    {}
func (*TaobaoProductHistory) Descriptor() ([]byte, []int) {
	return fileDescriptor_taobao_8dc4eb4fd83dc173, []int{2}
}
func (m *TaobaoProductHistory) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TaobaoProductHistory.Unmarshal(m, b)
}
func (m *TaobaoProductHistory) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TaobaoProductHistory.Marshal(b, m, deterministic)
}
func (dst *TaobaoProductHistory) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TaobaoProductHistory.Merge(dst, src)
}
func (m *TaobaoProductHistory) XXX_Size() int {
	return xxx_messageInfo_TaobaoProductHistory.Size(m)
}
func (m *TaobaoProductHistory) XXX_DiscardUnknown() {
	xxx_messageInfo_TaobaoProductHistory.DiscardUnknown(m)
}

var xxx_messageInfo_TaobaoProductHistory proto.InternalMessageInfo

func (m *TaobaoProductHistory) GetSkus() []*TaobaoSKUInfo {
	if m != nil {
		return m.Skus
	}
	return nil
}

func (m *TaobaoProductHistory) GetLastUpdatedTime() int64 {
	if m != nil {
		return m.LastUpdatedTime
	}
	return 0
}

// TaobaoProperty - taobao property
type TaobaoProperty struct {
	RootIndex            int32    `protobuf:"varint,1,opt,name=rootIndex,proto3" json:"rootIndex,omitempty"`
	RootName             string   `protobuf:"bytes,2,opt,name=rootName,proto3" json:"rootName,omitempty"`
	Key                  string   `protobuf:"bytes,3,opt,name=key,proto3" json:"key,omitempty"`
	Value                string   `protobuf:"bytes,4,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TaobaoProperty) Reset()         { *m = TaobaoProperty{} }
func (m *TaobaoProperty) String() string { return proto.CompactTextString(m) }
func (*TaobaoProperty) ProtoMessage()    {}
func (*TaobaoProperty) Descriptor() ([]byte, []int) {
	return fileDescriptor_taobao_8dc4eb4fd83dc173, []int{3}
}
func (m *TaobaoProperty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TaobaoProperty.Unmarshal(m, b)
}
func (m *TaobaoProperty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TaobaoProperty.Marshal(b, m, deterministic)
}
func (dst *TaobaoProperty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TaobaoProperty.Merge(dst, src)
}
func (m *TaobaoProperty) XXX_Size() int {
	return xxx_messageInfo_TaobaoProperty.Size(m)
}
func (m *TaobaoProperty) XXX_DiscardUnknown() {
	xxx_messageInfo_TaobaoProperty.DiscardUnknown(m)
}

var xxx_messageInfo_TaobaoProperty proto.InternalMessageInfo

func (m *TaobaoProperty) GetRootIndex() int32 {
	if m != nil {
		return m.RootIndex
	}
	return 0
}

func (m *TaobaoProperty) GetRootName() string {
	if m != nil {
		return m.RootName
	}
	return ""
}

func (m *TaobaoProperty) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *TaobaoProperty) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

// TaobaoReviewTag - taobao review tag
type TaobaoReviewTag struct {
	Tag                  string   `protobuf:"bytes,1,opt,name=tag,proto3" json:"tag,omitempty"`
	Times                int32    `protobuf:"varint,2,opt,name=times,proto3" json:"times,omitempty"`
	Type                 int32    `protobuf:"varint,3,opt,name=type,proto3" json:"type,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TaobaoReviewTag) Reset()         { *m = TaobaoReviewTag{} }
func (m *TaobaoReviewTag) String() string { return proto.CompactTextString(m) }
func (*TaobaoReviewTag) ProtoMessage()    {}
func (*TaobaoReviewTag) Descriptor() ([]byte, []int) {
	return fileDescriptor_taobao_8dc4eb4fd83dc173, []int{4}
}
func (m *TaobaoReviewTag) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TaobaoReviewTag.Unmarshal(m, b)
}
func (m *TaobaoReviewTag) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TaobaoReviewTag.Marshal(b, m, deterministic)
}
func (dst *TaobaoReviewTag) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TaobaoReviewTag.Merge(dst, src)
}
func (m *TaobaoReviewTag) XXX_Size() int {
	return xxx_messageInfo_TaobaoReviewTag.Size(m)
}
func (m *TaobaoReviewTag) XXX_DiscardUnknown() {
	xxx_messageInfo_TaobaoReviewTag.DiscardUnknown(m)
}

var xxx_messageInfo_TaobaoReviewTag proto.InternalMessageInfo

func (m *TaobaoReviewTag) GetTag() string {
	if m != nil {
		return m.Tag
	}
	return ""
}

func (m *TaobaoReviewTag) GetTimes() int32 {
	if m != nil {
		return m.Times
	}
	return 0
}

func (m *TaobaoReviewTag) GetType() int32 {
	if m != nil {
		return m.Type
	}
	return 0
}

type TaobaoRelatedItem struct {
	ItemID               string   `protobuf:"bytes,1,opt,name=itemID,proto3" json:"itemID,omitempty"`
	Url                  string   `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	Name                 string   `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	IsCurrent            bool     `protobuf:"varint,4,opt,name=isCurrent,proto3" json:"isCurrent,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TaobaoRelatedItem) Reset()         { *m = TaobaoRelatedItem{} }
func (m *TaobaoRelatedItem) String() string { return proto.CompactTextString(m) }
func (*TaobaoRelatedItem) ProtoMessage()    {}
func (*TaobaoRelatedItem) Descriptor() ([]byte, []int) {
	return fileDescriptor_taobao_8dc4eb4fd83dc173, []int{5}
}
func (m *TaobaoRelatedItem) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TaobaoRelatedItem.Unmarshal(m, b)
}
func (m *TaobaoRelatedItem) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TaobaoRelatedItem.Marshal(b, m, deterministic)
}
func (dst *TaobaoRelatedItem) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TaobaoRelatedItem.Merge(dst, src)
}
func (m *TaobaoRelatedItem) XXX_Size() int {
	return xxx_messageInfo_TaobaoRelatedItem.Size(m)
}
func (m *TaobaoRelatedItem) XXX_DiscardUnknown() {
	xxx_messageInfo_TaobaoRelatedItem.DiscardUnknown(m)
}

var xxx_messageInfo_TaobaoRelatedItem proto.InternalMessageInfo

func (m *TaobaoRelatedItem) GetItemID() string {
	if m != nil {
		return m.ItemID
	}
	return ""
}

func (m *TaobaoRelatedItem) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *TaobaoRelatedItem) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *TaobaoRelatedItem) GetIsCurrent() bool {
	if m != nil {
		return m.IsCurrent
	}
	return false
}

// TaobaoProduct - taobao product
type TaobaoProduct struct {
	ItemID               string                  `protobuf:"bytes,1,opt,name=itemID,proto3" json:"itemID,omitempty"`
	Skus                 []*TaobaoSKUInfo        `protobuf:"bytes,2,rep,name=skus,proto3" json:"skus,omitempty"`
	Title                string                  `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Reviews              int32                   `protobuf:"varint,4,opt,name=reviews,proto3" json:"reviews,omitempty"`
	LastUpdatedTime      int64                   `protobuf:"varint,5,opt,name=lastUpdatedTime,proto3" json:"lastUpdatedTime,omitempty"`
	Attributes           []string                `protobuf:"bytes,6,rep,name=attributes,proto3" json:"attributes,omitempty"`
	Shop                 *TaobaoShopInfo         `protobuf:"bytes,7,opt,name=shop,proto3" json:"shop,omitempty"`
	SalesVolume          int32                   `protobuf:"varint,8,opt,name=salesVolume,proto3" json:"salesVolume,omitempty"`
	Pay                  []string                `protobuf:"bytes,9,rep,name=pay,proto3" json:"pay,omitempty"`
	Service              []string                `protobuf:"bytes,10,rep,name=service,proto3" json:"service,omitempty"`
	Wl                   string                  `protobuf:"bytes,11,opt,name=wl,proto3" json:"wl,omitempty"`
	LstHistory           []*TaobaoProductHistory `protobuf:"bytes,12,rep,name=lstHistory,proto3" json:"lstHistory,omitempty"`
	RootCategoryID       string                  `protobuf:"bytes,13,opt,name=rootCategoryID,proto3" json:"rootCategoryID,omitempty"`
	CategoryID           string                  `protobuf:"bytes,14,opt,name=categoryID,proto3" json:"categoryID,omitempty"`
	TbItemID             string                  `protobuf:"bytes,15,opt,name=tbItemID,proto3" json:"tbItemID,omitempty"`
	BrandValueID         string                  `protobuf:"bytes,16,opt,name=brandValueID,proto3" json:"brandValueID,omitempty"`
	FavCount             int32                   `protobuf:"varint,17,opt,name=favCount,proto3" json:"favCount,omitempty"`
	Imgs                 []string                `protobuf:"bytes,18,rep,name=imgs,proto3" json:"imgs,omitempty"`
	Props                []*TaobaoProperty       `protobuf:"bytes,19,rep,name=props,proto3" json:"props,omitempty"`
	ReviewTags           []*TaobaoReviewTag      `protobuf:"bytes,20,rep,name=reviewTags,proto3" json:"reviewTags,omitempty"`
	Price                float32                 `protobuf:"fixed32,21,opt,name=price,proto3" json:"price,omitempty"`
	RelatedItems         []*TaobaoRelatedItem    `protobuf:"bytes,22,rep,name=relatedItems,proto3" json:"relatedItems,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *TaobaoProduct) Reset()         { *m = TaobaoProduct{} }
func (m *TaobaoProduct) String() string { return proto.CompactTextString(m) }
func (*TaobaoProduct) ProtoMessage()    {}
func (*TaobaoProduct) Descriptor() ([]byte, []int) {
	return fileDescriptor_taobao_8dc4eb4fd83dc173, []int{6}
}
func (m *TaobaoProduct) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TaobaoProduct.Unmarshal(m, b)
}
func (m *TaobaoProduct) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TaobaoProduct.Marshal(b, m, deterministic)
}
func (dst *TaobaoProduct) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TaobaoProduct.Merge(dst, src)
}
func (m *TaobaoProduct) XXX_Size() int {
	return xxx_messageInfo_TaobaoProduct.Size(m)
}
func (m *TaobaoProduct) XXX_DiscardUnknown() {
	xxx_messageInfo_TaobaoProduct.DiscardUnknown(m)
}

var xxx_messageInfo_TaobaoProduct proto.InternalMessageInfo

func (m *TaobaoProduct) GetItemID() string {
	if m != nil {
		return m.ItemID
	}
	return ""
}

func (m *TaobaoProduct) GetSkus() []*TaobaoSKUInfo {
	if m != nil {
		return m.Skus
	}
	return nil
}

func (m *TaobaoProduct) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *TaobaoProduct) GetReviews() int32 {
	if m != nil {
		return m.Reviews
	}
	return 0
}

func (m *TaobaoProduct) GetLastUpdatedTime() int64 {
	if m != nil {
		return m.LastUpdatedTime
	}
	return 0
}

func (m *TaobaoProduct) GetAttributes() []string {
	if m != nil {
		return m.Attributes
	}
	return nil
}

func (m *TaobaoProduct) GetShop() *TaobaoShopInfo {
	if m != nil {
		return m.Shop
	}
	return nil
}

func (m *TaobaoProduct) GetSalesVolume() int32 {
	if m != nil {
		return m.SalesVolume
	}
	return 0
}

func (m *TaobaoProduct) GetPay() []string {
	if m != nil {
		return m.Pay
	}
	return nil
}

func (m *TaobaoProduct) GetService() []string {
	if m != nil {
		return m.Service
	}
	return nil
}

func (m *TaobaoProduct) GetWl() string {
	if m != nil {
		return m.Wl
	}
	return ""
}

func (m *TaobaoProduct) GetLstHistory() []*TaobaoProductHistory {
	if m != nil {
		return m.LstHistory
	}
	return nil
}

func (m *TaobaoProduct) GetRootCategoryID() string {
	if m != nil {
		return m.RootCategoryID
	}
	return ""
}

func (m *TaobaoProduct) GetCategoryID() string {
	if m != nil {
		return m.CategoryID
	}
	return ""
}

func (m *TaobaoProduct) GetTbItemID() string {
	if m != nil {
		return m.TbItemID
	}
	return ""
}

func (m *TaobaoProduct) GetBrandValueID() string {
	if m != nil {
		return m.BrandValueID
	}
	return ""
}

func (m *TaobaoProduct) GetFavCount() int32 {
	if m != nil {
		return m.FavCount
	}
	return 0
}

func (m *TaobaoProduct) GetImgs() []string {
	if m != nil {
		return m.Imgs
	}
	return nil
}

func (m *TaobaoProduct) GetProps() []*TaobaoProperty {
	if m != nil {
		return m.Props
	}
	return nil
}

func (m *TaobaoProduct) GetReviewTags() []*TaobaoReviewTag {
	if m != nil {
		return m.ReviewTags
	}
	return nil
}

func (m *TaobaoProduct) GetPrice() float32 {
	if m != nil {
		return m.Price
	}
	return 0
}

func (m *TaobaoProduct) GetRelatedItems() []*TaobaoRelatedItem {
	if m != nil {
		return m.RelatedItems
	}
	return nil
}

// TaobaoItem - taobao item
type TaobaoItem struct {
	ItemID               string   `protobuf:"bytes,1,opt,name=itemID,proto3" json:"itemID,omitempty"`
	Title                string   `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Img                  string   `protobuf:"bytes,3,opt,name=img,proto3" json:"img,omitempty"`
	Url                  string   `protobuf:"bytes,4,opt,name=url,proto3" json:"url,omitempty"`
	Shopname             string   `protobuf:"bytes,5,opt,name=shopname,proto3" json:"shopname,omitempty"`
	Shopid               string   `protobuf:"bytes,6,opt,name=shopid,proto3" json:"shopid,omitempty"`
	Shopurl              string   `protobuf:"bytes,7,opt,name=shopurl,proto3" json:"shopurl,omitempty"`
	Price                float32  `protobuf:"fixed32,8,opt,name=price,proto3" json:"price,omitempty"`
	Deal                 int32    `protobuf:"varint,9,opt,name=deal,proto3" json:"deal,omitempty"`
	Icons                []string `protobuf:"bytes,10,rep,name=icons,proto3" json:"icons,omitempty"`
	Location             string   `protobuf:"bytes,11,opt,name=location,proto3" json:"location,omitempty"`
	IsAD                 bool     `protobuf:"varint,12,opt,name=isAD,proto3" json:"isAD,omitempty"`
	StrDeal              string   `protobuf:"bytes,13,opt,name=strDeal,proto3" json:"strDeal,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TaobaoItem) Reset()         { *m = TaobaoItem{} }
func (m *TaobaoItem) String() string { return proto.CompactTextString(m) }
func (*TaobaoItem) ProtoMessage()    {}
func (*TaobaoItem) Descriptor() ([]byte, []int) {
	return fileDescriptor_taobao_8dc4eb4fd83dc173, []int{7}
}
func (m *TaobaoItem) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TaobaoItem.Unmarshal(m, b)
}
func (m *TaobaoItem) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TaobaoItem.Marshal(b, m, deterministic)
}
func (dst *TaobaoItem) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TaobaoItem.Merge(dst, src)
}
func (m *TaobaoItem) XXX_Size() int {
	return xxx_messageInfo_TaobaoItem.Size(m)
}
func (m *TaobaoItem) XXX_DiscardUnknown() {
	xxx_messageInfo_TaobaoItem.DiscardUnknown(m)
}

var xxx_messageInfo_TaobaoItem proto.InternalMessageInfo

func (m *TaobaoItem) GetItemID() string {
	if m != nil {
		return m.ItemID
	}
	return ""
}

func (m *TaobaoItem) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *TaobaoItem) GetImg() string {
	if m != nil {
		return m.Img
	}
	return ""
}

func (m *TaobaoItem) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *TaobaoItem) GetShopname() string {
	if m != nil {
		return m.Shopname
	}
	return ""
}

func (m *TaobaoItem) GetShopid() string {
	if m != nil {
		return m.Shopid
	}
	return ""
}

func (m *TaobaoItem) GetShopurl() string {
	if m != nil {
		return m.Shopurl
	}
	return ""
}

func (m *TaobaoItem) GetPrice() float32 {
	if m != nil {
		return m.Price
	}
	return 0
}

func (m *TaobaoItem) GetDeal() int32 {
	if m != nil {
		return m.Deal
	}
	return 0
}

func (m *TaobaoItem) GetIcons() []string {
	if m != nil {
		return m.Icons
	}
	return nil
}

func (m *TaobaoItem) GetLocation() string {
	if m != nil {
		return m.Location
	}
	return ""
}

func (m *TaobaoItem) GetIsAD() bool {
	if m != nil {
		return m.IsAD
	}
	return false
}

func (m *TaobaoItem) GetStrDeal() string {
	if m != nil {
		return m.StrDeal
	}
	return ""
}

// TaobaoSearchResult - taobao search result
type TaobaoSearchResult struct {
	Items                []*TaobaoItem `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	Text                 string        `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	LastUpdatedTime      int64         `protobuf:"varint,3,opt,name=lastUpdatedTime,proto3" json:"lastUpdatedTime,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *TaobaoSearchResult) Reset()         { *m = TaobaoSearchResult{} }
func (m *TaobaoSearchResult) String() string { return proto.CompactTextString(m) }
func (*TaobaoSearchResult) ProtoMessage()    {}
func (*TaobaoSearchResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_taobao_8dc4eb4fd83dc173, []int{8}
}
func (m *TaobaoSearchResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TaobaoSearchResult.Unmarshal(m, b)
}
func (m *TaobaoSearchResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TaobaoSearchResult.Marshal(b, m, deterministic)
}
func (dst *TaobaoSearchResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TaobaoSearchResult.Merge(dst, src)
}
func (m *TaobaoSearchResult) XXX_Size() int {
	return xxx_messageInfo_TaobaoSearchResult.Size(m)
}
func (m *TaobaoSearchResult) XXX_DiscardUnknown() {
	xxx_messageInfo_TaobaoSearchResult.DiscardUnknown(m)
}

var xxx_messageInfo_TaobaoSearchResult proto.InternalMessageInfo

func (m *TaobaoSearchResult) GetItems() []*TaobaoItem {
	if m != nil {
		return m.Items
	}
	return nil
}

func (m *TaobaoSearchResult) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

func (m *TaobaoSearchResult) GetLastUpdatedTime() int64 {
	if m != nil {
		return m.LastUpdatedTime
	}
	return 0
}

// RequestTaobao - request taobao
type RequestTaobao struct {
	Mode                 TaobaoMode `protobuf:"varint,1,opt,name=mode,proto3,enum=jarviscrawlercore.TaobaoMode" json:"mode,omitempty"`
	ItemID               string     `protobuf:"bytes,2,opt,name=itemID,proto3" json:"itemID,omitempty"`
	Text                 string     `protobuf:"bytes,3,opt,name=text,proto3" json:"text,omitempty"`
	Device               string     `protobuf:"bytes,4,opt,name=device,proto3" json:"device,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *RequestTaobao) Reset()         { *m = RequestTaobao{} }
func (m *RequestTaobao) String() string { return proto.CompactTextString(m) }
func (*RequestTaobao) ProtoMessage()    {}
func (*RequestTaobao) Descriptor() ([]byte, []int) {
	return fileDescriptor_taobao_8dc4eb4fd83dc173, []int{9}
}
func (m *RequestTaobao) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RequestTaobao.Unmarshal(m, b)
}
func (m *RequestTaobao) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RequestTaobao.Marshal(b, m, deterministic)
}
func (dst *RequestTaobao) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RequestTaobao.Merge(dst, src)
}
func (m *RequestTaobao) XXX_Size() int {
	return xxx_messageInfo_RequestTaobao.Size(m)
}
func (m *RequestTaobao) XXX_DiscardUnknown() {
	xxx_messageInfo_RequestTaobao.DiscardUnknown(m)
}

var xxx_messageInfo_RequestTaobao proto.InternalMessageInfo

func (m *RequestTaobao) GetMode() TaobaoMode {
	if m != nil {
		return m.Mode
	}
	return TaobaoMode_TBM_PRODUCT
}

func (m *RequestTaobao) GetItemID() string {
	if m != nil {
		return m.ItemID
	}
	return ""
}

func (m *RequestTaobao) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

func (m *RequestTaobao) GetDevice() string {
	if m != nil {
		return m.Device
	}
	return ""
}

// ReplyTaobao - reply taobao
type ReplyTaobao struct {
	Mode TaobaoMode `protobuf:"varint,1,opt,name=mode,proto3,enum=jarviscrawlercore.TaobaoMode" json:"mode,omitempty"`
	// Types that are valid to be assigned to Reply:
	//	*ReplyTaobao_Product
	//	*ReplyTaobao_SearchResult
	Reply                isReplyTaobao_Reply `protobuf_oneof:"reply"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *ReplyTaobao) Reset()         { *m = ReplyTaobao{} }
func (m *ReplyTaobao) String() string { return proto.CompactTextString(m) }
func (*ReplyTaobao) ProtoMessage()    {}
func (*ReplyTaobao) Descriptor() ([]byte, []int) {
	return fileDescriptor_taobao_8dc4eb4fd83dc173, []int{10}
}
func (m *ReplyTaobao) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReplyTaobao.Unmarshal(m, b)
}
func (m *ReplyTaobao) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReplyTaobao.Marshal(b, m, deterministic)
}
func (dst *ReplyTaobao) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReplyTaobao.Merge(dst, src)
}
func (m *ReplyTaobao) XXX_Size() int {
	return xxx_messageInfo_ReplyTaobao.Size(m)
}
func (m *ReplyTaobao) XXX_DiscardUnknown() {
	xxx_messageInfo_ReplyTaobao.DiscardUnknown(m)
}

var xxx_messageInfo_ReplyTaobao proto.InternalMessageInfo

type isReplyTaobao_Reply interface {
	isReplyTaobao_Reply()
}

type ReplyTaobao_Product struct {
	Product *TaobaoProduct `protobuf:"bytes,100,opt,name=product,proto3,oneof"`
}
type ReplyTaobao_SearchResult struct {
	SearchResult *TaobaoSearchResult `protobuf:"bytes,101,opt,name=searchResult,proto3,oneof"`
}

func (*ReplyTaobao_Product) isReplyTaobao_Reply()      {}
func (*ReplyTaobao_SearchResult) isReplyTaobao_Reply() {}

func (m *ReplyTaobao) GetReply() isReplyTaobao_Reply {
	if m != nil {
		return m.Reply
	}
	return nil
}

func (m *ReplyTaobao) GetMode() TaobaoMode {
	if m != nil {
		return m.Mode
	}
	return TaobaoMode_TBM_PRODUCT
}

func (m *ReplyTaobao) GetProduct() *TaobaoProduct {
	if x, ok := m.GetReply().(*ReplyTaobao_Product); ok {
		return x.Product
	}
	return nil
}

func (m *ReplyTaobao) GetSearchResult() *TaobaoSearchResult {
	if x, ok := m.GetReply().(*ReplyTaobao_SearchResult); ok {
		return x.SearchResult
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*ReplyTaobao) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _ReplyTaobao_OneofMarshaler, _ReplyTaobao_OneofUnmarshaler, _ReplyTaobao_OneofSizer, []interface{}{
		(*ReplyTaobao_Product)(nil),
		(*ReplyTaobao_SearchResult)(nil),
	}
}

func _ReplyTaobao_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*ReplyTaobao)
	// reply
	switch x := m.Reply.(type) {
	case *ReplyTaobao_Product:
		b.EncodeVarint(100<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Product); err != nil {
			return err
		}
	case *ReplyTaobao_SearchResult:
		b.EncodeVarint(101<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.SearchResult); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("ReplyTaobao.Reply has unexpected type %T", x)
	}
	return nil
}

func _ReplyTaobao_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*ReplyTaobao)
	switch tag {
	case 100: // reply.product
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(TaobaoProduct)
		err := b.DecodeMessage(msg)
		m.Reply = &ReplyTaobao_Product{msg}
		return true, err
	case 101: // reply.searchResult
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(TaobaoSearchResult)
		err := b.DecodeMessage(msg)
		m.Reply = &ReplyTaobao_SearchResult{msg}
		return true, err
	default:
		return false, nil
	}
}

func _ReplyTaobao_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*ReplyTaobao)
	// reply
	switch x := m.Reply.(type) {
	case *ReplyTaobao_Product:
		s := proto.Size(x.Product)
		n += 2 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *ReplyTaobao_SearchResult:
		s := proto.Size(x.SearchResult)
		n += 2 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

func init() {
	proto.RegisterType((*TaobaoSKUInfo)(nil), "jarviscrawlercore.TaobaoSKUInfo")
	proto.RegisterType((*TaobaoShopInfo)(nil), "jarviscrawlercore.TaobaoShopInfo")
	proto.RegisterType((*TaobaoProductHistory)(nil), "jarviscrawlercore.TaobaoProductHistory")
	proto.RegisterType((*TaobaoProperty)(nil), "jarviscrawlercore.TaobaoProperty")
	proto.RegisterType((*TaobaoReviewTag)(nil), "jarviscrawlercore.TaobaoReviewTag")
	proto.RegisterType((*TaobaoRelatedItem)(nil), "jarviscrawlercore.TaobaoRelatedItem")
	proto.RegisterType((*TaobaoProduct)(nil), "jarviscrawlercore.TaobaoProduct")
	proto.RegisterType((*TaobaoItem)(nil), "jarviscrawlercore.TaobaoItem")
	proto.RegisterType((*TaobaoSearchResult)(nil), "jarviscrawlercore.TaobaoSearchResult")
	proto.RegisterType((*RequestTaobao)(nil), "jarviscrawlercore.RequestTaobao")
	proto.RegisterType((*ReplyTaobao)(nil), "jarviscrawlercore.ReplyTaobao")
	proto.RegisterEnum("jarviscrawlercore.TaobaoMode", TaobaoMode_name, TaobaoMode_value)
}

func init() { proto.RegisterFile("taobao.proto", fileDescriptor_taobao_8dc4eb4fd83dc173) }

var fileDescriptor_taobao_8dc4eb4fd83dc173 = []byte{
	// 1151 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x56, 0x4d, 0x6f, 0x1b, 0x37,
	0x13, 0x8e, 0x3e, 0x56, 0x1f, 0x63, 0x47, 0xb6, 0xf9, 0x26, 0x01, 0x11, 0xe4, 0x2d, 0x94, 0x45,
	0x3f, 0x84, 0x1e, 0x0c, 0x34, 0x69, 0xd1, 0x4b, 0x2f, 0xb1, 0x95, 0xd6, 0x42, 0xe2, 0xc6, 0x60,
	0xec, 0x5c, 0x0b, 0x5a, 0x4b, 0xcb, 0x5b, 0xaf, 0x96, 0x5b, 0x92, 0x2b, 0x47, 0x7f, 0xa0, 0xfd,
	0x31, 0xbd, 0xe7, 0x47, 0xf4, 0xdc, 0x1f, 0x54, 0xcc, 0x90, 0x6b, 0xad, 0x52, 0xd9, 0x45, 0x7b,
	0x9b, 0x67, 0x76, 0x48, 0x0e, 0x39, 0xcf, 0x33, 0xb3, 0xb0, 0xed, 0xa4, 0x3e, 0x97, 0x7a, 0xbf,
	0x30, 0xda, 0x69, 0xb6, 0xf7, 0xb3, 0x34, 0x8b, 0xd4, 0x4e, 0x8d, 0xbc, 0xce, 0x94, 0x99, 0x6a,
	0xa3, 0xe2, 0xdf, 0x1b, 0x70, 0xff, 0x94, 0x62, 0xde, 0xbe, 0x3a, 0x9b, 0xe4, 0x17, 0x9a, 0x3d,
	0x80, 0xc8, 0x5e, 0x95, 0x69, 0xc2, 0x1b, 0xc3, 0xc6, 0xa8, 0x2f, 0x3c, 0x40, 0x6f, 0x61, 0xd2,
	0xa9, 0xe2, 0xcd, 0x61, 0x63, 0xd4, 0x14, 0x1e, 0xa0, 0xd7, 0xa5, 0x2e, 0x53, 0xbc, 0xe5, 0x63,
	0x09, 0xb0, 0x5d, 0x68, 0xa5, 0xf3, 0x19, 0x6f, 0x93, 0x0f, 0x4d, 0xda, 0xd3, 0xe9, 0xe9, 0x15,
	0x8f, 0x86, 0x8d, 0x51, 0x24, 0x3c, 0x60, 0x1c, 0xba, 0x0b, 0x99, 0x95, 0x2a, 0x4d, 0x78, 0x87,
	0x62, 0x2b, 0xc8, 0x1e, 0x41, 0x27, 0x75, 0x6a, 0x9e, 0x26, 0xbc, 0x4b, 0x1f, 0x02, 0x8a, 0x3f,
	0xb4, 0x60, 0x10, 0xb2, 0xbd, 0xd4, 0x05, 0xa5, 0xcb, 0xa0, 0x9d, 0xcb, 0xb9, 0x0a, 0xd9, 0x92,
	0x8d, 0xbe, 0x99, 0xce, 0x12, 0xca, 0xb5, 0x27, 0xc8, 0xc6, 0xa4, 0x4a, 0x93, 0x85, 0x44, 0xd1,
	0xc4, 0x28, 0x23, 0xf3, 0xab, 0x90, 0x27, 0xd9, 0x78, 0xb0, 0x91, 0x2e, 0xcd, 0x67, 0x21, 0xd3,
	0x80, 0xd8, 0x13, 0xe8, 0x1b, 0xe9, 0xd4, 0x6b, 0xb5, 0x50, 0x19, 0xef, 0x0c, 0x5b, 0xa3, 0x48,
	0xac, 0x1c, 0xd5, 0xd7, 0xb7, 0xf8, 0xa2, 0xbc, 0x3b, 0x6c, 0x8d, 0x9a, 0x62, 0xe5, 0xc0, 0x3d,
	0xed, 0xa5, 0x2e, 0xd2, 0x84, 0xf7, 0xfc, 0x65, 0x3c, 0x42, 0x7f, 0x69, 0x95, 0x49, 0x13, 0xde,
	0xf7, 0x7e, 0x8f, 0xd8, 0x10, 0xb6, 0xa6, 0x46, 0x25, 0xa9, 0xf3, 0xa7, 0x01, 0x25, 0x52, 0x77,
	0xb1, 0x18, 0xb6, 0x65, 0x96, 0x4d, 0x9c, 0x9a, 0x1f, 0xea, 0x32, 0x77, 0x7c, 0x8b, 0x42, 0xd6,
	0x7c, 0x18, 0x93, 0xab, 0xeb, 0x55, 0xcc, 0xb6, 0x8f, 0xa9, 0xfb, 0xb0, 0x00, 0xd6, 0x99, 0xef,
	0x65, 0x6e, 0xf9, 0x7d, 0x5f, 0x80, 0x00, 0xd9, 0x3e, 0xb0, 0x99, 0xd6, 0x89, 0x90, 0x4e, 0x9d,
	0x28, 0x33, 0x55, 0xb9, 0x93, 0x33, 0xc5, 0x07, 0x54, 0xfb, 0x0d, 0x5f, 0xd8, 0x27, 0x00, 0x78,
	0xe1, 0x37, 0x17, 0x17, 0x56, 0x39, 0xbe, 0x43, 0x4f, 0x50, 0xf3, 0xc4, 0x0b, 0x78, 0xe0, 0xeb,
	0x76, 0x62, 0x74, 0x52, 0x4e, 0xdd, 0x51, 0x6a, 0x9d, 0x36, 0x4b, 0xf6, 0x35, 0xb4, 0xed, 0x55,
	0x69, 0x79, 0x63, 0xd8, 0x1a, 0x6d, 0x3d, 0x1b, 0xee, 0xff, 0x8d, 0xa0, 0xfb, 0x6b, 0xe4, 0x14,
	0x14, 0xcd, 0x46, 0xb0, 0x93, 0x49, 0xeb, 0xce, 0x8a, 0x44, 0x3a, 0x95, 0x9c, 0xa6, 0x73, 0x4f,
	0xcb, 0x96, 0xf8, 0xd8, 0x1d, 0x9b, 0x8a, 0x2f, 0x27, 0x46, 0x17, 0xca, 0xb8, 0x25, 0xd5, 0x4a,
	0x6b, 0x37, 0xc9, 0x13, 0xf5, 0x9e, 0x48, 0x83, 0x95, 0xac, 0x1c, 0xec, 0x31, 0xf4, 0x10, 0xfc,
	0x28, 0xc3, 0x96, 0x7d, 0x71, 0x83, 0x91, 0x41, 0x57, 0x6a, 0x59, 0x31, 0xe8, 0x4a, 0x2d, 0x91,
	0xd6, 0xc4, 0xd8, 0x40, 0x21, 0x0f, 0xe2, 0x63, 0xd8, 0xf1, 0x67, 0x0a, 0xb5, 0x48, 0xd5, 0xf5,
	0xa9, 0x9c, 0xe1, 0x52, 0x27, 0x67, 0x81, 0xa3, 0x68, 0x7a, 0xe5, 0xcc, 0x95, 0xa5, 0x53, 0x22,
	0xe1, 0x01, 0x52, 0xd2, 0x2d, 0x0b, 0x2f, 0xa7, 0x48, 0x90, 0x1d, 0x6b, 0xd8, 0xab, 0xb6, 0xcb,
	0xf0, 0x5e, 0x58, 0xbe, 0x4a, 0x20, 0x93, 0x71, 0xd8, 0x33, 0xa0, 0x8a, 0xe5, 0xcd, 0x35, 0x96,
	0x93, 0x3e, 0x5a, 0x35, 0x7d, 0x3c, 0x81, 0x7e, 0x6a, 0x0f, 0x4b, 0x63, 0x54, 0xee, 0x28, 0xf7,
	0x9e, 0x58, 0x39, 0xe2, 0x3f, 0x3a, 0x55, 0x4b, 0x08, 0xc5, 0xba, 0xf5, 0xb4, 0xaa, 0x7a, 0xcd,
	0x7f, 0x55, 0xbd, 0xcd, 0x4d, 0x83, 0x43, 0xd7, 0xd0, 0x7b, 0x59, 0xca, 0x28, 0x12, 0x15, 0xdc,
	0x54, 0xed, 0x68, 0x63, 0xb5, 0x91, 0x85, 0xd2, 0x39, 0x93, 0x9e, 0x97, 0x4e, 0x59, 0x92, 0x69,
	0x5f, 0xd4, 0x3c, 0xec, 0x1b, 0x68, 0xa3, 0xf6, 0xa8, 0xa9, 0x6c, 0x3d, 0x7b, 0x7a, 0x7b, 0xbe,
	0xa1, 0xb9, 0x08, 0x0a, 0x47, 0x41, 0x5a, 0x99, 0x29, 0xfb, 0x4e, 0x67, 0xe5, 0x5c, 0x91, 0x8a,
	0x23, 0x51, 0x77, 0xe1, 0xb3, 0x17, 0x72, 0xc9, 0xfb, 0x74, 0x22, 0x9a, 0x24, 0x2d, 0x65, 0x16,
	0xd8, 0x31, 0x81, 0xbc, 0x15, 0x64, 0x03, 0x68, 0x5e, 0x67, 0x24, 0xd9, 0xbe, 0x68, 0x5e, 0x67,
	0xec, 0x07, 0x80, 0xcc, 0x56, 0x82, 0xe0, 0xdb, 0xf4, 0x94, 0x5f, 0xdc, 0x9a, 0xda, 0xba, 0x7e,
	0x44, 0x6d, 0x29, 0xfb, 0x1c, 0x06, 0xc8, 0xd5, 0x43, 0xe9, 0xd4, 0x4c, 0x9b, 0xe5, 0x64, 0x1c,
	0x44, 0xfd, 0x91, 0x17, 0x5f, 0x69, 0xba, 0x8a, 0x19, 0x50, 0x4c, 0xcd, 0x83, 0x1a, 0x70, 0xe7,
	0x13, 0x5f, 0xef, 0x1d, 0xaf, 0x81, 0x0a, 0x63, 0x57, 0x39, 0x37, 0x32, 0x4f, 0xde, 0x21, 0xd3,
	0x27, 0x63, 0xbe, 0x4b, 0xdf, 0xd7, 0x7c, 0xb8, 0xfe, 0x42, 0x2e, 0x7c, 0xd7, 0xd9, 0xa3, 0xb7,
	0xba, 0xc1, 0xc8, 0xc6, 0x74, 0x3e, 0xb3, 0x9c, 0xd1, 0x9b, 0x90, 0xcd, 0xbe, 0xc5, 0xd1, 0xa2,
	0x0b, 0xcb, 0xff, 0x47, 0x77, 0x7f, 0x7a, 0xd7, 0xdd, 0x49, 0xc3, 0xc2, 0xc7, 0xb3, 0x03, 0x00,
	0x53, 0x49, 0xcc, 0xf2, 0x07, 0xb4, 0x3a, 0xbe, 0x75, 0xf5, 0x8d, 0x1a, 0x45, 0x6d, 0xd5, 0x6a,
	0xae, 0x3d, 0xac, 0xcf, 0xb5, 0x23, 0xd8, 0x36, 0x2b, 0xb5, 0x59, 0xfe, 0x88, 0xf6, 0xfe, 0xf4,
	0x8e, 0xbd, 0x6f, 0x82, 0xc5, 0xda, 0xca, 0xf8, 0x43, 0x13, 0xc0, 0xc7, 0xdc, 0xa9, 0xdb, 0x1b,
	0x4d, 0x34, 0x37, 0x0c, 0xd2, 0xd6, 0x6a, 0x90, 0x06, 0x7d, 0xb7, 0x57, 0xfa, 0x7e, 0x0c, 0x3d,
	0x24, 0x29, 0x69, 0x3c, 0xf2, 0xd5, 0xaa, 0x70, 0x6d, 0xf2, 0x74, 0xd6, 0x26, 0x0f, 0x92, 0xf3,
	0x52, 0x17, 0xb8, 0x53, 0x37, 0xf4, 0x7d, 0x0f, 0x57, 0xcf, 0xd1, 0xab, 0x3f, 0x07, 0x83, 0x76,
	0xa2, 0x64, 0x46, 0x73, 0x2a, 0x12, 0x64, 0x63, 0x64, 0x3a, 0xd5, 0xb9, 0x0d, 0xf4, 0xf6, 0x00,
	0xb3, 0xc9, 0xf4, 0x54, 0xba, 0x54, 0xe7, 0x81, 0xe2, 0x37, 0x98, 0x6a, 0x6f, 0x5f, 0x8c, 0x69,
	0x12, 0xf5, 0x04, 0xd9, 0x61, 0x02, 0x8d, 0x71, 0xf3, 0xd5, 0x04, 0x42, 0x18, 0xff, 0xd6, 0x00,
	0x16, 0xd4, 0xa8, 0xa4, 0x99, 0x5e, 0x0a, 0x65, 0xcb, 0xcc, 0xb1, 0xe7, 0x10, 0xa5, 0x54, 0x12,
	0x3f, 0x31, 0xfe, 0x7f, 0x6b, 0x49, 0xa8, 0x16, 0x3e, 0x96, 0xda, 0xaa, 0x7a, 0xef, 0xc2, 0xe3,
	0x92, 0xbd, 0xa9, 0xab, 0xb4, 0x36, 0xcf, 0x90, 0x5f, 0x1b, 0x70, 0x5f, 0xa8, 0x5f, 0x4a, 0x65,
	0x9d, 0xdf, 0x9a, 0x7d, 0x05, 0xed, 0xb9, 0x4e, 0xfc, 0x3f, 0xc7, 0xe0, 0x8e, 0x1c, 0x8e, 0x75,
	0xa2, 0x04, 0x85, 0xd6, 0x0a, 0xdf, 0x5c, 0x2b, 0x7c, 0x95, 0x5a, 0xab, 0x96, 0xda, 0x23, 0xe8,
	0x24, 0x8a, 0x5a, 0x87, 0xaf, 0x73, 0x40, 0xf1, 0x9f, 0x0d, 0xd8, 0x12, 0xaa, 0xc8, 0x96, 0xff,
	0x3d, 0x8d, 0xef, 0xa0, 0x5b, 0xf8, 0x0e, 0xc2, 0x13, 0x6a, 0x82, 0xc3, 0x7f, 0xec, 0x34, 0xf7,
	0x44, 0xb5, 0x84, 0xbd, 0x82, 0x6d, 0x5b, 0x2b, 0x06, 0x57, 0xb4, 0xc5, 0x67, 0xb7, 0xf7, 0xd1,
	0x5a, 0xf0, 0xd1, 0x3d, 0xb1, 0xb6, 0xf8, 0xa0, 0x0b, 0x91, 0xc1, 0xcb, 0x7c, 0x39, 0xae, 0x14,
	0x82, 0x79, 0xb2, 0x1d, 0xd8, 0x3a, 0x3d, 0x38, 0xfe, 0xe9, 0x44, 0xbc, 0x19, 0x9f, 0x1d, 0x9e,
	0xee, 0xde, 0x63, 0x03, 0x00, 0x74, 0xbc, 0x7d, 0xf9, 0x42, 0x1c, 0x1e, 0xed, 0x36, 0xd8, 0x43,
	0xd8, 0x43, 0x7c, 0xfc, 0xe6, 0x60, 0xf2, 0xfa, 0x65, 0x15, 0xd6, 0x3c, 0xef, 0xd0, 0x2f, 0xee,
	0xf3, 0xbf, 0x02, 0x00, 0x00, 0xff, 0xff, 0x0b, 0x9a, 0x87, 0xae, 0xf2, 0x0a, 0x00, 0x00,
}
