# clients - array of the clients
clients:
- servaddr: 127.0.0.1:7051
  token: wzDkh9h2fhfUVuS9jZ8uVbhV3vC5AWX3
  tags:
  - localhost
- servaddr: 127.0.0.1:7052
  token: wzDkh9h2fhfUVuS9jZ8uVbhV3vC5AWX3
  tags:
  - localhost
  - china

# maxmultifailtimes - If the client fail {{maxmultifailtimes}} times in succession, it need to ignore some task
maxmultifailtimes: 3
# effectivefailtime - If the interval between 2 failures is less than {{effectivefailtime}} seconds, it should be counted as a multiple failure.
effectivefailtime: 180
# ignoretasktime - The client will ignore the task for {{ignoretasktime}} seconds.
ignoretasktime: 300

# database root path
dbpath: ./data
# database engine
dbengine: leveldb